<?php

/**
 * Constants
 */

const SUPPORTED_LANGUAGES = [
    'nl' => ['flag' => '🇳🇱', 'label' => 'Nederlands'],
    'en' => ['flag' => '🇬🇧', 'label' => 'English'],
    'de' => ['flag' => '🇩🇪', 'label' => 'Deutsch'],
    'fr' => ['flag' => '🇫🇷', 'label' => 'Français'],
];

const TRANSLATIONS = [
    /* ------------------------------------------------------------------ */
    'nl' => [
        // Header
        'header.title' => 'ICT ticketsysteem',
        'header.subtitle_admin' => 'Beheer alle tickets, behandel reacties en verdeel werk slim over ICT.',
        'header.subtitle_user' => 'Maak eenvoudig een ICT-ticket aan en volg je meldingen.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'Nieuw ticket',
        'nav.ict_overview' => 'ICT-overzicht',
        'nav.settings' => 'Instellingen',
        'nav.ict_stats' => 'ICT-stats',

        // Ticket list
        'tickets.heading_admin' => 'ICT ticketoverzicht',
        'tickets.heading_user' => 'Mijn tickets',
        'filter.status_label' => 'Status filter',
        'filter.category_label' => 'Categorie filter',
        'filter.ict_employee' => 'ICT-medewerker',
        'filter.all_assigned' => 'Alle toegewezen',
        'filter.unassigned' => 'Nog niet toegewezen',
        'filter.reset' => 'Reset filters',
        'tickets.empty_admin' => 'Er zijn nog geen tickets die aan deze filters voldoen.',
        'tickets.empty_user' => 'Je hebt nog geen tickets.',
        'ticket.messages_count' => 'berichten',
        'ticket.time_open' => 'tijd open',
        'ticket.meta_created' => 'Aangemaakt op · Tijd open',
        'ticket.meta_updated' => 'Laatst bijgewerkt',
        'ticket.meta_priority' => 'Prioriteit',
        'ticket.priority_0' => '0 · Normaal',
        'ticket.priority_1' => '1 · Belemmerd',
        'ticket.priority_2' => '2 · Geblokkeerd',
        'ticket.messages_heading' => 'Berichten',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Gebruiker',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Toewijzen aan',
        'ticket.unassigned' => 'Nog niet toegewezen',
        'ticket.new_message' => 'Nieuw bericht',
        'ticket.new_message_placeholder' => 'Typ hier een update of aanvullende informatie.',
        'ticket.reopen' => 'Ticket weer openen',
        'ticket.add_attachments' => 'Bijlagen toevoegen',
        'ticket.file_hint' => 'Per bestand maximaal 20 MB.',
        'ticket.btn_save' => 'Opslaan',
        'ticket.btn_reply' => 'Reactie plaatsen en ICT mailen',

        // New ticket form
        'new_ticket.heading' => 'Nieuw ticket maken',
        'new_ticket.intro' => 'Een ticket krijgt automatisch een ICT-medewerker toegewezen op basis van categorie en actuele openstaande werkdruk.',
        'new_ticket.title_label' => 'Titel',
        'new_ticket.title_placeholder' => 'Bijvoorbeeld: Nieuwe scanner nodig',
        'new_ticket.category_label' => 'Categorie',
        'new_ticket.category_option' => 'Kies een categorie',
        'new_ticket.description_label' => 'Beschrijving',
        'new_ticket.description_placeholder' => 'Beschrijf het probleem of de aanvraag zo duidelijk mogelijk.',
        'new_ticket.blocked' => 'Mijn werkzaamheden worden belemmerd',
        'new_ticket.fully_blocked' => 'Ik kan niet verder werken tot dit opgelost is',
        'new_ticket.requester_label' => 'Gebruiker',
        'new_ticket.requester_placeholder' => 'naam@kvt.nl (optioneel, voor ticket namens iemand anders)',
        'new_ticket.requester_hint' => 'Alleen voor ICT: dit e-mailadres wordt als aanvrager gebruikt als je het invult.',
        'new_ticket.attachments_label' => 'Screenshots of documenten',
        'new_ticket.btn_submit' => 'Ticket indienen',

        // Settings
        'settings.heading' => 'Instellingen per ICT-gebruiker',
        'settings.intro' => 'Zet per ICT-collega categorieën aan of uit en markeer medewerkers als afwezig. Nieuwe tickets worden automatisch toegewezen aan de minst belaste beschikbare collega.',
        'settings.col_user' => 'ICT-gebruiker',
        'settings.col_open_tickets' => 'Open tickets',
        'settings.btn_save' => 'Instellingen opslaan',
        'settings.db_exists' => 'bestaat',
        'settings.db_missing' => 'ontbreekt',
        'settings.dir_writable' => 'map schrijfbaar',
        'settings.file_writable' => 'bestand schrijfbaar',
        'settings.yes' => 'ja',
        'settings.no' => 'nee',

        // Statistics
        'stats.heading' => 'ICT-statistieken',
        'stats.intro' => 'Bekijk hier de totalen, prestaties per ICT-medewerker en wachttijden per normale gebruiker. Voor afgehandelde tickets meten we van <strong>aangemaakt</strong> tot <strong>afgehandeld</strong>; open tickets tellen mee tot <strong>nu</strong>.',
        'stats.total_tickets' => 'Totaal aantal tickets',
        'stats.open_tickets' => 'Openstaande tickets',
        'stats.resolved_tickets' => 'Afgehandelde tickets',
        'stats.waiting_order' => 'Wacht op bestelling',
        'stats.per_ict' => 'Per ICT-medewerker',
        'stats.col_ict_employee' => 'ICT-medewerker',
        'stats.col_handled' => 'Afgehandeld',
        'stats.col_avg_open' => 'Gemiddelde tijd open',
        'stats.col_max_open' => 'Langste open tijd',
        'stats.col_outstanding' => 'Openstaand',
        'stats.col_waiting_order' => 'Wacht op bestelling',
        'stats.per_user' => 'Per normale gebruiker',
        'stats.no_user_stats' => 'Er zijn nog geen statistieken voor normale gebruikers beschikbaar.',
        'stats.col_user' => 'Gebruiker',
        'stats.col_submitted' => 'Tickets ingediend',
        'stats.col_avg_wait' => 'Gemiddelde wachttijd',
        'stats.col_max_wait' => 'Langste wachttijd',
        'stats.wait_note' => 'Wachttijden bij gebruikers worden berekend op basis van tickets met status <strong>afgehandeld</strong>.',
        'stats.sidebar_heading' => 'Openstaande tickets',
        'stats.sidebar_empty' => 'Geen openstaande tickets.',
        'stats.no_assigned' => 'Niet toegewezen',

        // Flash messages / errors
        'flash.admin_only' => 'Alleen ICT-gebruikers hebben toegang tot het ticketoverzicht.',
        'flash.attachment_not_found' => 'Bijlage niet gevonden.',
        'flash.attachment_missing' => 'Het bestand ontbreekt op de server.',
        'flash.session_expired' => 'Je sessie is verlopen. Ververs de pagina en probeer het opnieuw.',
        'flash.db_open_error' => 'De database kon niet worden geopend: %s',
        'flash.ticket_title_required' => 'Vul een titel in voor het ticket.',
        'flash.invalid_category' => 'Kies een geldige categorie.',
        'flash.description_required' => 'Vul een beschrijving in.',
        'flash.blocked_inconsistent' => 'Je kunt alleen aangeven dat je niet verder kunt werken als werkzaamheden al belemmerd zijn.',
        'flash.invalid_email' => 'Vul een geldig e-mailadres in bij Gebruiker.',
        'flash.ticket_created' => 'Ticket #%d is aangemaakt en automatisch toegewezen.',
        'flash.ticket_not_found' => 'Ticket niet gevonden of niet toegankelijk.',
        'flash.invalid_status' => 'Kies een geldige status.',
        'flash.invalid_employee' => 'Kies een geldige ICT-medewerker.',
        'flash.employee_away' => 'Deze ICT-medewerker staat als afwezig gemarkeerd en kan geen nieuwe tickets ontvangen.',
        'flash.invalid_priority' => 'Kies een geldige prioriteit.',
        'flash.reply_empty' => 'Voeg een bericht, bijlage of statuswijziging toe.',
        'flash.ticket_updated' => 'Ticket #%d is bijgewerkt.',
        'flash.settings_admin_only' => 'Alleen admins kunnen instellingen aanpassen.',
        'flash.settings_saved' => 'De categorie-instellingen en afwezigheid voor ICT zijn opgeslagen.',
        'flash.unknown_action' => 'Onbekende actie ontvangen.',
        'flash.db_error_prefix' => 'Databasefout:',

        // Ticketstatus-weergavelabels (DB-sleutel → vertaalde weergave)
        'status.ingediend' => 'ingediend',
        'status.in_behandeling' => 'in behandeling',
        'status.afwachtende_op_gebruiker' => 'afwachtende op gebruiker',
        'status.afwachtende_op_bestelling' => 'afwachtende op bestelling',
        'status.afgehandeld' => 'afgehandeld',

        // Categorieweergavelabels (DB-sleutel → vertaalde weergave)
        'category.hardware_bestellen' => 'hardware bestellen',
        'category.software_bestellen' => 'software bestellen',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'Hardwareproblemen',
        'category.softwareproblemen' => 'Softwareproblemen',
        'category.web_app_problemen' => 'sleutels.kvt.nl web-applicatieproblemen',
        'category.anders' => 'Anders',

        // Prioriteitslabels (zonder getal-prefix; voor formatPriorityLabel)
        'priority.label.0' => 'Normaal',
        'priority.label.1' => 'Belemmerd',
        'priority.label.2' => 'Geblokkeerd',

        // Tijdseenheden voor formatDurationSeconds
        'duration.year' => 'jaar',
        'duration.years' => 'jaar',
        'duration.month' => 'maand',
        'duration.months' => 'maanden',
        'duration.week' => 'week',
        'duration.weeks' => 'weken',
        'duration.day' => 'dag',
        'duration.days' => 'dagen',
        'duration.hour' => 'uur',
        'duration.hours' => 'uur',
        'duration.minute' => 'minuut',
        'duration.minutes' => 'minuten',
        'duration.less_than_minute' => 'minder dan 1 minuut',

        // Diverse helpers
        'datetime.unknown' => 'Onbekend',
        'flash.status_changed_to' => 'Status gewijzigd naar %s.',
        'flash.attachment_upload_error' => 'Bijlage "%s" kon niet worden geüpload.',
        'flash.attachment_too_large' => 'Bijlage "%s" is groter dan 20 MB.',
    ],

    /* ------------------------------------------------------------------ */
    'en' => [
        // Header
        'header.title' => 'ICT ticket system',
        'header.subtitle_admin' => 'Manage all tickets, handle replies and distribute work across ICT.',
        'header.subtitle_user' => 'Easily create an ICT ticket and track your reports.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'New ticket',
        'nav.ict_overview' => 'ICT overview',
        'nav.settings' => 'Settings',
        'nav.ict_stats' => 'ICT stats',

        // Ticket list
        'tickets.heading_admin' => 'ICT ticket overview',
        'tickets.heading_user' => 'My tickets',
        'filter.status_label' => 'Status filter',
        'filter.category_label' => 'Category filter',
        'filter.ict_employee' => 'ICT employee',
        'filter.all_assigned' => 'All assigned',
        'filter.unassigned' => 'Not yet assigned',
        'filter.reset' => 'Reset filters',
        'tickets.empty_admin' => 'There are no tickets matching these filters yet.',
        'tickets.empty_user' => 'You have no tickets yet.',
        'ticket.messages_count' => 'messages',
        'ticket.time_open' => 'time open',
        'ticket.meta_created' => 'Created at · Time open',
        'ticket.meta_updated' => 'Last updated',
        'ticket.meta_priority' => 'Priority',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Impeded',
        'ticket.priority_2' => '2 · Blocked',
        'ticket.messages_heading' => 'Messages',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'User',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Assign to',
        'ticket.unassigned' => 'Not yet assigned',
        'ticket.new_message' => 'New message',
        'ticket.new_message_placeholder' => 'Type an update or additional information here.',
        'ticket.reopen' => 'Reopen ticket',
        'ticket.add_attachments' => 'Add attachments',
        'ticket.file_hint' => 'Maximum 20 MB per file.',
        'ticket.btn_save' => 'Save',
        'ticket.btn_reply' => 'Post reply and email ICT',

        // New ticket form
        'new_ticket.heading' => 'Create new ticket',
        'new_ticket.intro' => 'A ticket is automatically assigned to an ICT employee based on category and current workload.',
        'new_ticket.title_label' => 'Title',
        'new_ticket.title_placeholder' => 'For example: New scanner needed',
        'new_ticket.category_label' => 'Category',
        'new_ticket.category_option' => 'Choose a category',
        'new_ticket.description_label' => 'Description',
        'new_ticket.description_placeholder' => 'Describe the problem or request as clearly as possible.',
        'new_ticket.blocked' => 'My work is being impeded',
        'new_ticket.fully_blocked' => 'I cannot continue working until this is resolved',
        'new_ticket.requester_label' => 'User',
        'new_ticket.requester_placeholder' => 'name@kvt.nl (optional, to create a ticket on behalf of someone else)',
        'new_ticket.requester_hint' => 'ICT only: this e-mail address will be used as the requester if filled in.',
        'new_ticket.attachments_label' => 'Screenshots or documents',
        'new_ticket.btn_submit' => 'Submit ticket',

        // Settings
        'settings.heading' => 'Settings per ICT user',
        'settings.intro' => 'Enable or disable categories per ICT colleague and mark employees as absent. New tickets are automatically assigned to the least busy available colleague.',
        'settings.col_user' => 'ICT user',
        'settings.col_open_tickets' => 'Open tickets',
        'settings.btn_save' => 'Save settings',
        'settings.db_exists' => 'exists',
        'settings.db_missing' => 'missing',
        'settings.dir_writable' => 'directory writable',
        'settings.file_writable' => 'file writable',
        'settings.yes' => 'yes',
        'settings.no' => 'no',

        // Statistics
        'stats.heading' => 'ICT statistics',
        'stats.intro' => 'View totals, performance per ICT employee and waiting times per regular user. For resolved tickets we measure from <strong>created</strong> to <strong>resolved</strong>; open tickets count up to <strong>now</strong>.',
        'stats.total_tickets' => 'Total tickets',
        'stats.open_tickets' => 'Open tickets',
        'stats.resolved_tickets' => 'Resolved tickets',
        'stats.waiting_order' => 'Waiting for order',
        'stats.per_ict' => 'Per ICT employee',
        'stats.col_ict_employee' => 'ICT employee',
        'stats.col_handled' => 'Resolved',
        'stats.col_avg_open' => 'Average time open',
        'stats.col_max_open' => 'Longest open time',
        'stats.col_outstanding' => 'Outstanding',
        'stats.col_waiting_order' => 'Waiting for order',
        'stats.per_user' => 'Per regular user',
        'stats.no_user_stats' => 'No statistics for regular users are available yet.',
        'stats.col_user' => 'User',
        'stats.col_submitted' => 'Tickets submitted',
        'stats.col_avg_wait' => 'Average wait time',
        'stats.col_max_wait' => 'Longest wait time',
        'stats.wait_note' => 'Wait times for users are calculated based on tickets with status <strong>resolved</strong>.',
        'stats.sidebar_heading' => 'Open tickets',
        'stats.sidebar_empty' => 'No open tickets.',
        'stats.no_assigned' => 'Not assigned',

        // Flash messages / errors
        'flash.admin_only' => 'Only ICT users have access to the ticket overview.',
        'flash.attachment_not_found' => 'Attachment not found.',
        'flash.attachment_missing' => 'The file is missing on the server.',
        'flash.session_expired' => 'Your session has expired. Please refresh the page and try again.',
        'flash.db_open_error' => 'The database could not be opened: %s',
        'flash.ticket_title_required' => 'Please enter a title for the ticket.',
        'flash.invalid_category' => 'Please choose a valid category.',
        'flash.description_required' => 'Please enter a description.',
        'flash.blocked_inconsistent' => 'You can only indicate that you cannot continue working if your work is already impeded.',
        'flash.invalid_email' => 'Please enter a valid e-mail address in the User field.',
        'flash.ticket_created' => 'Ticket #%d has been created and automatically assigned.',
        'flash.ticket_not_found' => 'Ticket not found or not accessible.',
        'flash.invalid_status' => 'Please choose a valid status.',
        'flash.invalid_employee' => 'Please choose a valid ICT employee.',
        'flash.employee_away' => 'This ICT employee is marked as absent and cannot receive new tickets.',
        'flash.invalid_priority' => 'Please choose a valid priority.',
        'flash.reply_empty' => 'Please add a message, attachment or status change.',
        'flash.ticket_updated' => 'Ticket #%d has been updated.',
        'flash.settings_admin_only' => 'Only admins can change settings.',
        'flash.settings_saved' => 'Category settings and ICT absences have been saved.',
        'flash.unknown_action' => 'Unknown action received.',
        'flash.db_error_prefix' => 'Database error:',

        // Ticket status display labels
        'status.ingediend' => 'submitted',
        'status.in_behandeling' => 'in progress',
        'status.afwachtende_op_gebruiker' => 'awaiting user',
        'status.afwachtende_op_bestelling' => 'awaiting order',
        'status.afgehandeld' => 'resolved',

        // Category display labels
        'category.hardware_bestellen' => 'order hardware',
        'category.software_bestellen' => 'order software',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'hardware problems',
        'category.softwareproblemen' => 'software problems',
        'category.web_app_problemen' => 'sleutels.kvt.nl web application problems',
        'category.anders' => 'Other',

        // Priority labels (without number prefix)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Impeded',
        'priority.label.2' => 'Blocked',

        // Duration units for formatDurationSeconds
        'duration.year' => 'year',
        'duration.years' => 'years',
        'duration.month' => 'month',
        'duration.months' => 'months',
        'duration.week' => 'week',
        'duration.weeks' => 'weeks',
        'duration.day' => 'day',
        'duration.days' => 'days',
        'duration.hour' => 'hour',
        'duration.hours' => 'hours',
        'duration.minute' => 'minute',
        'duration.minutes' => 'minutes',
        'duration.less_than_minute' => 'less than 1 minute',

        // Misc helpers
        'datetime.unknown' => 'Unknown',
        'flash.status_changed_to' => 'Status changed to %s.',
        'flash.attachment_upload_error' => 'Attachment "%s" could not be uploaded.',
        'flash.attachment_too_large' => 'Attachment "%s" is larger than 20 MB.',
    ],

    /* ------------------------------------------------------------------ */
    'de' => [
        // Header
        'header.title' => 'ICT-Ticketsystem',
        'header.subtitle_admin' => 'Verwalten Sie alle Tickets, bearbeiten Sie Antworten und verteilen Sie Aufgaben effizient im ICT-Team.',
        'header.subtitle_user' => 'Erstellen Sie ganz einfach ein ICT-Ticket und verfolgen Sie Ihre Meldungen.',
        'header.admin_suffix' => ' · Admin',
        'nav.new_ticket' => 'Neues Ticket',
        'nav.ict_overview' => 'ICT-Übersicht',
        'nav.settings' => 'Einstellungen',
        'nav.ict_stats' => 'ICT-Statistiken',

        // Ticket list
        'tickets.heading_admin' => 'ICT-Ticketübersicht',
        'tickets.heading_user' => 'Meine Tickets',
        'filter.status_label' => 'Statusfilter',
        'filter.category_label' => 'Kategoriefilter',
        'filter.ict_employee' => 'ICT-Mitarbeiter',
        'filter.all_assigned' => 'Alle zugewiesen',
        'filter.unassigned' => 'Noch nicht zugewiesen',
        'filter.reset' => 'Filter zurücksetzen',
        'tickets.empty_admin' => 'Es gibt noch keine Tickets, die diesen Filtern entsprechen.',
        'tickets.empty_user' => 'Sie haben noch keine Tickets.',
        'ticket.messages_count' => 'Nachrichten',
        'ticket.time_open' => 'Offen seit',
        'ticket.meta_created' => 'Erstellt am · Offen seit',
        'ticket.meta_updated' => 'Zuletzt aktualisiert',
        'ticket.meta_priority' => 'Priorität',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Beeinträchtigt',
        'ticket.priority_2' => '2 · Blockiert',
        'ticket.messages_heading' => 'Nachrichten',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Benutzer',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Zuweisen an',
        'ticket.unassigned' => 'Noch nicht zugewiesen',
        'ticket.new_message' => 'Neue Nachricht',
        'ticket.new_message_placeholder' => 'Geben Sie hier eine Aktualisierung oder zusätzliche Informationen ein.',
        'ticket.reopen' => 'Ticket wieder öffnen',
        'ticket.add_attachments' => 'Anhänge hinzufügen',
        'ticket.file_hint' => 'Maximal 20 MB pro Datei.',
        'ticket.btn_save' => 'Speichern',
        'ticket.btn_reply' => 'Antwort senden und ICT benachrichtigen',

        // New ticket form
        'new_ticket.heading' => 'Neues Ticket erstellen',
        'new_ticket.intro' => 'Ein Ticket wird automatisch einem ICT-Mitarbeiter zugewiesen, basierend auf Kategorie und aktueller Arbeitsbelastung.',
        'new_ticket.title_label' => 'Titel',
        'new_ticket.title_placeholder' => 'Zum Beispiel: Neuer Scanner benötigt',
        'new_ticket.category_label' => 'Kategorie',
        'new_ticket.category_option' => 'Kategorie wählen',
        'new_ticket.description_label' => 'Beschreibung',
        'new_ticket.description_placeholder' => 'Beschreiben Sie das Problem oder die Anfrage so genau wie möglich.',
        'new_ticket.blocked' => 'Meine Arbeit wird beeinträchtigt',
        'new_ticket.fully_blocked' => 'Ich kann nicht weiterarbeiten, bis dies gelöst ist',
        'new_ticket.requester_label' => 'Benutzer',
        'new_ticket.requester_placeholder' => 'name@kvt.nl (optional, um ein Ticket im Namen einer anderen Person zu erstellen)',
        'new_ticket.requester_hint' => 'Nur für ICT: Diese E-Mail-Adresse wird als Anfrager verwendet, wenn sie ausgefüllt ist.',
        'new_ticket.attachments_label' => 'Screenshots oder Dokumente',
        'new_ticket.btn_submit' => 'Ticket einreichen',

        // Settings
        'settings.heading' => 'Einstellungen pro ICT-Benutzer',
        'settings.intro' => 'Aktivieren oder deaktivieren Sie Kategorien pro ICT-Kollegen und markieren Sie Mitarbeiter als abwesend. Neue Tickets werden automatisch dem am wenigsten ausgelasteten verfügbaren Kollegen zugewiesen.',
        'settings.col_user' => 'ICT-Benutzer',
        'settings.col_open_tickets' => 'Offene Tickets',
        'settings.btn_save' => 'Einstellungen speichern',
        'settings.db_exists' => 'vorhanden',
        'settings.db_missing' => 'fehlt',
        'settings.dir_writable' => 'Verzeichnis beschreibbar',
        'settings.file_writable' => 'Datei beschreibbar',
        'settings.yes' => 'ja',
        'settings.no' => 'nein',

        // Statistics
        'stats.heading' => 'ICT-Statistiken',
        'stats.intro' => 'Hier sehen Sie die Gesamtzahlen, Leistungen pro ICT-Mitarbeiter und Wartezeiten pro Benutzer. Bei erledigten Tickets messen wir von <strong>erstellt</strong> bis <strong>erledigt</strong>; offene Tickets zählen bis <strong>jetzt</strong>.',
        'stats.total_tickets' => 'Tickets insgesamt',
        'stats.open_tickets' => 'Offene Tickets',
        'stats.resolved_tickets' => 'Erledigte Tickets',
        'stats.waiting_order' => 'Wartet auf Bestellung',
        'stats.per_ict' => 'Pro ICT-Mitarbeiter',
        'stats.col_ict_employee' => 'ICT-Mitarbeiter',
        'stats.col_handled' => 'Erledigt',
        'stats.col_avg_open' => 'Durchschnittliche Offenzeit',
        'stats.col_max_open' => 'Längste Offenzeit',
        'stats.col_outstanding' => 'Ausstehend',
        'stats.col_waiting_order' => 'Wartet auf Bestellung',
        'stats.per_user' => 'Pro normalen Benutzer',
        'stats.no_user_stats' => 'Es sind noch keine Statistiken für normale Benutzer verfügbar.',
        'stats.col_user' => 'Benutzer',
        'stats.col_submitted' => 'Eingereichte Tickets',
        'stats.col_avg_wait' => 'Durchschnittliche Wartezeit',
        'stats.col_max_wait' => 'Längste Wartezeit',
        'stats.wait_note' => 'Wartezeiten für Benutzer werden auf Grundlage von Tickets mit Status <strong>erledigt</strong> berechnet.',
        'stats.sidebar_heading' => 'Offene Tickets',
        'stats.sidebar_empty' => 'Keine offenen Tickets.',
        'stats.no_assigned' => 'Nicht zugewiesen',

        // Flash messages / errors
        'flash.admin_only' => 'Nur ICT-Benutzer haben Zugriff auf die Ticketübersicht.',
        'flash.attachment_not_found' => 'Anhang nicht gefunden.',
        'flash.attachment_missing' => 'Die Datei fehlt auf dem Server.',
        'flash.session_expired' => 'Ihre Sitzung ist abgelaufen. Bitte laden Sie die Seite neu und versuchen Sie es erneut.',
        'flash.db_open_error' => 'Die Datenbank konnte nicht geöffnet werden: %s',
        'flash.ticket_title_required' => 'Bitte geben Sie einen Titel für das Ticket ein.',
        'flash.invalid_category' => 'Bitte wählen Sie eine gültige Kategorie.',
        'flash.description_required' => 'Bitte geben Sie eine Beschreibung ein.',
        'flash.blocked_inconsistent' => 'Sie können nur angeben, dass Sie nicht weiterarbeiten können, wenn Ihre Arbeit bereits beeinträchtigt ist.',
        'flash.invalid_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse im Feld Benutzer ein.',
        'flash.ticket_created' => 'Ticket #%d wurde erstellt und automatisch zugewiesen.',
        'flash.ticket_not_found' => 'Ticket nicht gefunden oder nicht zugänglich.',
        'flash.invalid_status' => 'Bitte wählen Sie einen gültigen Status.',
        'flash.invalid_employee' => 'Bitte wählen Sie einen gültigen ICT-Mitarbeiter.',
        'flash.employee_away' => 'Dieser ICT-Mitarbeiter ist als abwesend markiert und kann keine neuen Tickets erhalten.',
        'flash.invalid_priority' => 'Bitte wählen Sie eine gültige Priorität.',
        'flash.reply_empty' => 'Bitte fügen Sie eine Nachricht, einen Anhang oder eine Statusänderung hinzu.',
        'flash.ticket_updated' => 'Ticket #%d wurde aktualisiert.',
        'flash.settings_admin_only' => 'Nur Admins können Einstellungen ändern.',
        'flash.settings_saved' => 'Die Kategorieeinstellungen und ICT-Abwesenheiten wurden gespeichert.',
        'flash.unknown_action' => 'Unbekannte Aktion empfangen.',
        'flash.db_error_prefix' => 'Datenbankfehler:',

        // Ticketstatus-Anzeigebezeichnungen
        'status.ingediend' => 'eingereicht',
        'status.in_behandeling' => 'in Bearbeitung',
        'status.afwachtende_op_gebruiker' => 'wartet auf Benutzer',
        'status.afwachtende_op_bestelling' => 'wartet auf Bestellung',
        'status.afgehandeld' => 'erledigt',

        // Kategorieanzeigebezeichnungen
        'category.hardware_bestellen' => 'Hardware bestellen',
        'category.software_bestellen' => 'Software bestellen',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'Hardwareprobleme',
        'category.softwareproblemen' => 'Softwareprobleme',
        'category.web_app_problemen' => 'sleutels.kvt.nl Web-Anwendungsprobleme',
        'category.anders' => 'Sonstiges',

        // Prioritätsbezeichnungen (ohne Zahlenpräfix)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Beeinträchtigt',
        'priority.label.2' => 'Blockiert',

        // Zeiteinheiten für formatDurationSeconds
        'duration.year' => 'Jahr',
        'duration.years' => 'Jahre',
        'duration.month' => 'Monat',
        'duration.months' => 'Monate',
        'duration.week' => 'Woche',
        'duration.weeks' => 'Wochen',
        'duration.day' => 'Tag',
        'duration.days' => 'Tage',
        'duration.hour' => 'Stunde',
        'duration.hours' => 'Stunden',
        'duration.minute' => 'Minute',
        'duration.minutes' => 'Minuten',
        'duration.less_than_minute' => 'weniger als 1 Minute',

        // Sonstiges
        'datetime.unknown' => 'Unbekannt',
        'flash.status_changed_to' => 'Status geändert auf %s.',
        'flash.attachment_upload_error' => 'Anhang "%s" konnte nicht hochgeladen werden.',
        'flash.attachment_too_large' => 'Anhang "%s" ist größer als 20 MB.',
    ],

    /* ------------------------------------------------------------------ */
    'fr' => [
        // Header
        'header.title' => 'Système de tickets ICT',
        'header.subtitle_admin' => 'Gérez tous les tickets, traitez les réponses et répartissez le travail efficacement au sein de l\'équipe ICT.',
        'header.subtitle_user' => 'Créez facilement un ticket ICT et suivez vos signalements.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'Nouveau ticket',
        'nav.ict_overview' => 'Vue d\'ensemble ICT',
        'nav.settings' => 'Paramètres',
        'nav.ict_stats' => 'Statistiques ICT',

        // Ticket list
        'tickets.heading_admin' => 'Vue d\'ensemble des tickets ICT',
        'tickets.heading_user' => 'Mes tickets',
        'filter.status_label' => 'Filtre par statut',
        'filter.category_label' => 'Filtre par catégorie',
        'filter.ict_employee' => 'Employé ICT',
        'filter.all_assigned' => 'Tous les assignés',
        'filter.unassigned' => 'Non encore assigné',
        'filter.reset' => 'Réinitialiser les filtres',
        'tickets.empty_admin' => 'Il n\'y a encore aucun ticket correspondant à ces filtres.',
        'tickets.empty_user' => 'Vous n\'avez encore aucun ticket.',
        'ticket.messages_count' => 'messages',
        'ticket.time_open' => 'temps ouvert',
        'ticket.meta_created' => 'Créé le · Temps ouvert',
        'ticket.meta_updated' => 'Dernière mise à jour',
        'ticket.meta_priority' => 'Priorité',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Entravé',
        'ticket.priority_2' => '2 · Bloqué',
        'ticket.messages_heading' => 'Messages',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Utilisateur',
        'ticket.status_label' => 'Statut',
        'ticket.assigned_to' => 'Assigner à',
        'ticket.unassigned' => 'Non encore assigné',
        'ticket.new_message' => 'Nouveau message',
        'ticket.new_message_placeholder' => 'Saisissez ici une mise à jour ou des informations supplémentaires.',
        'ticket.reopen' => 'Rouvrir le ticket',
        'ticket.add_attachments' => 'Ajouter des pièces jointes',
        'ticket.file_hint' => '20 Mo maximum par fichier.',
        'ticket.btn_save' => 'Enregistrer',
        'ticket.btn_reply' => 'Publier la réponse et envoyer un e-mail à l\'ICT',

        // New ticket form
        'new_ticket.heading' => 'Créer un nouveau ticket',
        'new_ticket.intro' => 'Un ticket est automatiquement attribué à un employé ICT en fonction de la catégorie et de la charge de travail actuelle.',
        'new_ticket.title_label' => 'Titre',
        'new_ticket.title_placeholder' => 'Par exemple : Nouveau scanner nécessaire',
        'new_ticket.category_label' => 'Catégorie',
        'new_ticket.category_option' => 'Choisir une catégorie',
        'new_ticket.description_label' => 'Description',
        'new_ticket.description_placeholder' => 'Décrivez le problème ou la demande aussi clairement que possible.',
        'new_ticket.blocked' => 'Mon travail est entravé',
        'new_ticket.fully_blocked' => 'Je ne peux pas continuer à travailler jusqu\'à ce que ce problème soit résolu',
        'new_ticket.requester_label' => 'Utilisateur',
        'new_ticket.requester_placeholder' => 'nom@kvt.nl (facultatif, pour créer un ticket au nom de quelqu\'un d\'autre)',
        'new_ticket.requester_hint' => 'ICT uniquement : cette adresse e-mail sera utilisée comme demandeur si elle est renseignée.',
        'new_ticket.attachments_label' => 'Captures d\'écran ou documents',
        'new_ticket.btn_submit' => 'Soumettre le ticket',

        // Settings
        'settings.heading' => 'Paramètres par utilisateur ICT',
        'settings.intro' => 'Activez ou désactivez des catégories par collègue ICT et marquez les employés absents. Les nouveaux tickets sont automatiquement attribués au collègue disponible le moins chargé.',
        'settings.col_user' => 'Utilisateur ICT',
        'settings.col_open_tickets' => 'Tickets ouverts',
        'settings.btn_save' => 'Enregistrer les paramètres',
        'settings.db_exists' => 'existe',
        'settings.db_missing' => 'manquant',
        'settings.dir_writable' => 'répertoire accessible en écriture',
        'settings.file_writable' => 'fichier accessible en écriture',
        'settings.yes' => 'oui',
        'settings.no' => 'non',

        // Statistics
        'stats.heading' => 'Statistiques ICT',
        'stats.intro' => 'Consultez ici les totaux, les performances par employé ICT et les temps d\'attente par utilisateur. Pour les tickets résolus, nous mesurons de <strong>créé</strong> à <strong>résolu</strong> ; les tickets ouverts comptent jusqu\'à <strong>maintenant</strong>.',
        'stats.total_tickets' => 'Nombre total de tickets',
        'stats.open_tickets' => 'Tickets ouverts',
        'stats.resolved_tickets' => 'Tickets résolus',
        'stats.waiting_order' => 'En attente de commande',
        'stats.per_ict' => 'Par employé ICT',
        'stats.col_ict_employee' => 'Employé ICT',
        'stats.col_handled' => 'Résolu',
        'stats.col_avg_open' => 'Temps ouvert moyen',
        'stats.col_max_open' => 'Temps ouvert le plus long',
        'stats.col_outstanding' => 'En cours',
        'stats.col_waiting_order' => 'En attente de commande',
        'stats.per_user' => 'Par utilisateur standard',
        'stats.no_user_stats' => 'Aucune statistique n\'est encore disponible pour les utilisateurs standard.',
        'stats.col_user' => 'Utilisateur',
        'stats.col_submitted' => 'Tickets soumis',
        'stats.col_avg_wait' => 'Temps d\'attente moyen',
        'stats.col_max_wait' => 'Temps d\'attente le plus long',
        'stats.wait_note' => 'Les temps d\'attente des utilisateurs sont calculés sur la base des tickets ayant le statut <strong>résolu</strong>.',
        'stats.sidebar_heading' => 'Tickets ouverts',
        'stats.sidebar_empty' => 'Aucun ticket ouvert.',
        'stats.no_assigned' => 'Non assigné',

        // Flash messages / errors
        'flash.admin_only' => 'Seuls les utilisateurs ICT ont accès à la vue d\'ensemble des tickets.',
        'flash.attachment_not_found' => 'Pièce jointe introuvable.',
        'flash.attachment_missing' => 'Le fichier est manquant sur le serveur.',
        'flash.session_expired' => 'Votre session a expiré. Veuillez actualiser la page et réessayer.',
        'flash.db_open_error' => 'La base de données n\'a pas pu être ouverte : %s',
        'flash.ticket_title_required' => 'Veuillez saisir un titre pour le ticket.',
        'flash.invalid_category' => 'Veuillez choisir une catégorie valide.',
        'flash.description_required' => 'Veuillez saisir une description.',
        'flash.blocked_inconsistent' => 'Vous ne pouvez indiquer que vous ne pouvez pas continuer à travailler que si votre travail est déjà entravé.',
        'flash.invalid_email' => 'Veuillez saisir une adresse e-mail valide dans le champ Utilisateur.',
        'flash.ticket_created' => 'Le ticket #%d a été créé et automatiquement attribué.',
        'flash.ticket_not_found' => 'Ticket introuvable ou inaccessible.',
        'flash.invalid_status' => 'Veuillez choisir un statut valide.',
        'flash.invalid_employee' => 'Veuillez choisir un employé ICT valide.',
        'flash.employee_away' => 'Cet employé ICT est marqué comme absent et ne peut pas recevoir de nouveaux tickets.',
        'flash.invalid_priority' => 'Veuillez choisir une priorité valide.',
        'flash.reply_empty' => 'Veuillez ajouter un message, une pièce jointe ou un changement de statut.',
        'flash.ticket_updated' => 'Le ticket #%d a été mis à jour.',
        'flash.settings_admin_only' => 'Seuls les administrateurs peuvent modifier les paramètres.',
        'flash.settings_saved' => 'Les paramètres de catégorie et les absences ICT ont été enregistrés.',
        'flash.unknown_action' => 'Action inconnue reçue.',
        'flash.db_error_prefix' => 'Erreur de base de données :',

        // Libellés d'affichage des statuts
        'status.ingediend' => 'soumis',
        'status.in_behandeling' => 'en cours',
        'status.afwachtende_op_gebruiker' => 'en attente de l\'utilisateur',
        'status.afwachtende_op_bestelling' => 'en attente de commande',
        'status.afgehandeld' => 'résolu',

        // Libellés d'affichage des catégories
        'category.hardware_bestellen' => 'commander du matériel',
        'category.software_bestellen' => 'commander un logiciel',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'problèmes matériels',
        'category.softwareproblemen' => 'problèmes logiciels',
        'category.web_app_problemen' => 'problèmes d\'application web sleutels.kvt.nl',
        'category.anders' => 'Autre',

        // Libellés de priorité (sans préfixe numérique)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Entravé',
        'priority.label.2' => 'Bloqué',

        // Unités de temps pour formatDurationSeconds
        'duration.year' => 'an',
        'duration.years' => 'ans',
        'duration.month' => 'mois',
        'duration.months' => 'mois',
        'duration.week' => 'semaine',
        'duration.weeks' => 'semaines',
        'duration.day' => 'jour',
        'duration.days' => 'jours',
        'duration.hour' => 'heure',
        'duration.hours' => 'heures',
        'duration.minute' => 'minute',
        'duration.minutes' => 'minutes',
        'duration.less_than_minute' => 'moins d\'1 minute',

        // Divers
        'datetime.unknown' => 'Inconnu',
        'flash.status_changed_to' => 'Statut modifié en %s.',
        'flash.attachment_upload_error' => 'La pièce jointe "%s" n\'a pas pu être téléchargée.',
        'flash.attachment_too_large' => 'La pièce jointe "%s" dépasse 20 Mo.',
    ],
];

/**
 * Functies
 */

function getCurrentLanguage(): string
{
    return (string) ($_SESSION['lang'] ?? 'nl');
}

/**
 * Geeft de vertaling voor $key in de actieve taal.
 * Extra $args worden via sprintf ingevoegd (voor %d, %s, etc.).
 */
function __(string $key, mixed ...$args): string
{
    $lang = getCurrentLanguage();
    $translations = TRANSLATIONS[$lang] ?? TRANSLATIONS['nl'];
    $string = $translations[$key] ?? (TRANSLATIONS['nl'][$key] ?? $key);

    return $args !== [] ? sprintf($string, ...$args) : $string;
}

/**
 * Page load
 */

if (isset($_GET['lang']) && array_key_exists($_GET['lang'], SUPPORTED_LANGUAGES)) {
    $_SESSION['lang'] = $_GET['lang'];
}
