<?php

/**
 * Constants
 */

const SUPPORTED_LANGUAGES = [
    'nl' => ['flag' => '🇳🇱', 'label' => 'Nederlands'],
    'en' => ['flag' => '🇬🇧', 'label' => 'English'],
    'de' => ['flag' => '🇩🇪', 'label' => 'Deutsch'],
    'fr' => ['flag' => '🇫🇷', 'label' => 'Français'],
];

const TRANSLATIONS = [
    /* ------------------------------------------------------------------ */
    'nl' => [
        // Header
        'header.title' => 'ICT ticketsysteem',
        'header.subtitle_admin' => 'Beheer alle tickets, behandel reacties en verdeel werk slim over ICT.',
        'header.subtitle_user' => 'Maak eenvoudig een ICT-ticket aan en volg je meldingen.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'Nieuw ticket',
        'nav.ict_overview' => 'ICT-overzicht',
        'nav.settings' => 'Instellingen',
        'nav.ict_stats' => 'ICT-stats',
        'nav.template_tickets' => 'Template tickets',

        // Ticket list
        'tickets.heading_admin' => 'ICT ticketoverzicht',
        'tickets.heading_user' => 'Mijn tickets',
        'filter.status_label' => 'Status filter',
        'filter.category_label' => 'Categorie filter',
        'filter.search_label' => 'Zoeken',
        'filter.search_placeholder' => 'Zoek op ticketnummer, e-mail, naam, tekst of datum',
        'filter.ict_employee' => 'ICT-medewerker',
        'filter.all_assigned' => 'Alle toegewezen',
        'filter.unassigned' => 'Nog niet toegewezen',
        'filter.reset' => 'Reset filters',
        'tickets.empty_admin' => 'Er zijn nog geen tickets die aan deze filters voldoen.',
        'tickets.empty_user' => 'Je hebt nog geen tickets.',
        'ticket.messages_count' => 'berichten',
        'ticket.time_open' => 'tijd open',
        'ticket.meta_created' => 'Aangemaakt op · Tijd open',
        'ticket.meta_updated' => 'Laatst bijgewerkt',
        'ticket.meta_due_date' => 'Uiterste datum',
        'ticket.meta_priority' => 'Prioriteit',
        'ticket.priority_0' => '0 · Normaal',
        'ticket.priority_1' => '1 · Belemmerd',
        'ticket.priority_2' => '2 · Geblokkeerd',
        'ticket.messages_heading' => 'Berichten',
        'ticket.thread_loading' => 'Berichten laden…',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Gebruiker',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Toewijzen aan',
        'ticket.participants_title' => 'Gebruikers op dit ticket',
        'ticket.participants_admin_heading' => 'Gebruikers beheren',
        'ticket.participant_creator' => 'Aangemaakt door',
        'ticket.participant_remove' => 'Verwijderen',
        'ticket.participants_add_label' => 'Gebruikers toevoegen',
        'ticket.participants_add_placeholder' => 'Typ e-mailadressen, gescheiden door komma\'s',
        'ticket.participants_add_button' => 'Gebruikers toevoegen',
        'ticket.participants_save_button' => 'Opslaan',
        'ticket.manage_participants_button' => 'Gebruikers beheren',
        'ticket.participant_remove_confirm' => 'Wil je %s markeren om te verwijderen?',
        'ticket.participant_note_added' => 'Gebruikers toegevoegd: %s',
        'ticket.participant_note_removed' => 'Gebruikers verwijderd: %s',
        'ticket.unassigned' => 'Nog niet toegewezen',
        'ticket.new_message' => 'Nieuw bericht',
        'ticket.new_message_placeholder' => 'Typ hier een update of aanvullende informatie.',
        'ticket.key_picker_tooltip' => 'Toetsenbord snelkoppelingen invoegen',
        'ticket.emoji_picker_tooltip' => 'Emoji invoegen',
        'ticket.reopen' => 'Ticket weer openen',
        'ticket.add_attachments' => 'Bijlagen toevoegen',
        'ticket.preview_image' => 'Afbeelding vergroten',
        'ticket.preview_file' => 'Bestand voorvertonen',
        'ticket.preview_close' => 'Voorvertoning sluiten',
        'ticket.file_hint' => 'Per bestand maximaal 20 MB.',
        'ticket.btn_save' => 'Opslaan',
        'ticket.btn_reply' => 'Reactie plaatsen en ICT mailen',
        'ticket.show_original' => 'Toon origineel',
        'ticket.show_translation' => 'Toon vertaling',
        'translation.loading_tooltip' => 'Vertaling wordt geladen',
        'translation.error_tooltip' => 'Vertaling mislukt. Klik voor details.',
        'translation.error_title' => 'Vertaalfout',
        'translation.error_fallback' => 'Er is een fout opgetreden bij het laden van de vertaling.',

        // New ticket form
        'new_ticket.heading' => 'Nieuw ticket maken',
        'new_ticket.intro' => 'Een ticket krijgt automatisch een ICT-medewerker toegewezen op basis van categorie en actuele openstaande werkdruk.',
        'new_ticket.title_label' => 'Titel',
        'new_ticket.title_placeholder' => 'Bijvoorbeeld: Nieuwe scanner nodig',
        'new_ticket.category_label' => 'Categorie',
        'new_ticket.category_option' => 'Kies een categorie',
        'new_ticket.description_label' => 'Beschrijving',
        'new_ticket.description_placeholder' => 'Beschrijf het probleem of de aanvraag zo duidelijk mogelijk.',
        'new_ticket.blocked' => 'Mijn werkzaamheden worden belemmerd',
        'new_ticket.fully_blocked' => 'Ik kan niet verder werken tot dit opgelost is',
        'new_ticket.requester_label' => 'Gebruiker',
        'new_ticket.requester_list_label' => 'Gebruikers (eerste adres is aanvrager)',
        'new_ticket.requester_placeholder' => 'naam@kvt.nl (optioneel, voor ticket namens iemand anders)',
        'new_ticket.requester_hint' => 'Alleen voor ICT: dit e-mailadres wordt als aanvrager gebruikt als je het invult.',
        'new_ticket.requester_list_hint' => 'ICT: vul 1 of meer e-mailadressen in.',
        'new_ticket.participants_label' => 'Extra gebruikers',
        'new_ticket.participants_placeholder' => 'naam1@kvt.nl, naam2@kvt.nl',
        'new_ticket.participants_hint' => 'Voeg collega\'s toe die dit ticket ook onder Mijn tickets moeten zien.',
        'new_ticket.attachments_label' => 'Screenshots of documenten',
        'new_ticket.btn_submit' => 'Ticket indienen',

        // Template tickets
        'template_ticket.heading' => 'Template-ticket aanmaken',
        'template_ticket.intro' => 'Maak een ticket op basis van template-fragmenten en kies een template-categorie.',
        'template_ticket.category_label' => 'Template-categorie',
        'template_ticket.assignee_label' => 'Toewijzing',
        'template_ticket.assignee_auto' => 'Auto',
        'template_ticket.due_date_label' => 'Due-date',
        'template_ticket.title_label' => 'Ticket naam',
        'template_ticket.title_placeholder' => 'Bijvoorbeeld: Laptop voorbereiden voor nieuwe medewerker',
        'template_ticket.preview_label' => 'Ticket preview',
        'template_ticket.preview_hint' => 'De preview is de uiteindelijke ticketbeschrijving (template-teksten met newlines).',
        'template_ticket.create_button' => 'Template-ticket aanmaken',
        'template_ticket.templates_heading' => 'Template-fragmenten',
        'template_ticket.create_template_heading' => 'Template aanmaken',
        'template_ticket.edit_heading' => 'Template wijzigen',
        'template_ticket.template_name_label' => 'Naam',
        'template_ticket.template_name_placeholder' => 'Bijvoorbeeld: Nieuwe gebruiker setup',
        'template_ticket.template_body_label' => 'Tekst',
        'template_ticket.template_body_placeholder' => 'Typ hier het template-fragment.',
        'template_ticket.create_template_button' => 'Template opslaan',
        'template_ticket.save_template_button' => 'Wijzigingen opslaan',
        'template_ticket.delete_template_button' => 'Template verwijderen',
        'template_ticket.edit_template_button' => 'Wijzigen',
        'template_ticket.new_template_button' => 'Nieuw template',
        'template_ticket.modal_close' => 'Sluiten',
        'template_ticket.back_to_list' => 'Terug naar lijst',
        'template_ticket.delete_confirm' => 'Weet je zeker dat je dit template-fragment wilt verwijderen?',
        'template_ticket.empty_templates' => 'Er zijn nog geen template-fragmenten.',
        'template_ticket.select_template_error' => 'Selecteer minimaal 1 template-fragment.',

        // Settings
        'settings.heading' => 'Instellingen per ICT-gebruiker',
        'settings.intro' => 'Zet per ICT-collega categorieën aan of uit en markeer medewerkers als afwezig. Nieuwe tickets worden automatisch toegewezen aan de minst belaste beschikbare collega.',
        'settings.regular_categories_heading' => 'Reguliere ticketcategorieën',
        'settings.template_categories_heading' => 'Template-ticketcategorieën',
        'settings.col_user' => 'ICT-gebruiker',
        'settings.col_open_tickets' => 'Open tickets',
        'settings.btn_save' => 'Instellingen opslaan',
        'settings.db_exists' => 'bestaat',
        'settings.db_missing' => 'ontbreekt',
        'settings.dir_writable' => 'map schrijfbaar',
        'settings.file_writable' => 'bestand schrijfbaar',
        'settings.yes' => 'ja',
        'settings.no' => 'nee',

        // Statistics
        'stats.heading' => 'ICT-statistieken',
        'stats.intro' => 'Bekijk hier de totalen, prestaties per ICT-medewerker en wachttijden per normale gebruiker. Voor afgehandelde tickets meten we van <strong>aangemaakt</strong> tot <strong>afgehandeld</strong>; open tickets tellen mee tot <strong>nu</strong>.',
        'stats.total_tickets' => 'Totaal aantal tickets',
        'stats.open_tickets' => 'Openstaande tickets',
        'stats.resolved_tickets' => 'Afgehandelde tickets',
        'stats.waiting_order' => 'Wacht op bestelling',
        'stats.per_ict' => 'Per ICT-medewerker',
        'stats.col_ict_employee' => 'ICT-medewerker',
        'stats.col_handled' => 'Afgehandeld',
        'stats.col_avg_open' => 'Gemiddelde tijd open',
        'stats.col_max_open' => 'Langste open tijd',
        'stats.col_outstanding' => 'Openstaand',
        'stats.col_waiting_order' => 'Wacht op bestelling',
        'stats.per_user' => 'Per normale gebruiker',
        'stats.no_user_stats' => 'Er zijn nog geen statistieken voor normale gebruikers beschikbaar.',
        'stats.col_user' => 'Gebruiker',
        'stats.col_submitted' => 'Tickets ingediend',
        'stats.col_avg_wait' => 'Gemiddelde wachttijd',
        'stats.col_max_wait' => 'Langste wachttijd',
        'stats.col_avg_response' => 'Gemiddelde responstijd',
        'stats.wait_note' => '* Wachttijd telt alleen de tijd in status <strong>ingediend</strong>, <strong>in behandeling</strong> en <strong>afwachtende op bestelling</strong>. Tijd in <strong>afgehandeld</strong> en <strong>afwachtende op gebruiker</strong> telt niet mee. Gemiddelde responstijd is de gemiddelde tijd in <strong>afwachtende op gebruiker</strong>.',
        'stats.sidebar_heading' => 'Openstaande tickets',
        'stats.sidebar_empty' => 'Geen openstaande tickets.',
        'stats.no_assigned' => 'Niet toegewezen',
        'bs.card_changed' => '#%d gewijzigd',
        'bs.card_status' => 'Status: %s',
        'bs.card_assigned' => 'Toegewezen aan: %s',
        'bs.card_unassigned' => 'Niemand',
        'bs.card_new_message' => 'Nieuw bericht',
        'bs.no_user_stats' => 'Er zijn nog geen statistieken voor normale gebruikers beschikbaar.',
        'bs.col_user' => 'Gebruiker',
        'bs.col_submitted' => 'Tickets ingediend',
        'bs.col_avg_wait' => 'Gemiddelde wachttijd',
        'bs.col_max_wait' => 'Langste wachttijd',
        'bs.col_avg_response' => 'Gemiddelde responstijd',
        'bs.wait_note' => '* Wachttijd telt alleen de tijd in status <strong>ingediend</strong>, <strong>in behandeling</strong> en <strong>afwachtende op bestelling</strong>. Tijd in <strong>afgehandeld</strong> en <strong>afwachtende op gebruiker</strong> telt niet mee. Gemiddelde responstijd is de gemiddelde tijd in <strong>afwachtende op gebruiker</strong>.',
        'bs.new_ticket_from' => 'Nieuw ticket van %s!',
        'bs.assigned_to' => 'Toegewezen aan: %s',
        'bs.not_yet_assigned' => 'Nog niet toegewezen',

        // Flash messages / errors
        'flash.admin_only' => 'Alleen ICT-gebruikers hebben toegang tot het ticketoverzicht.',
        'flash.attachment_not_found' => 'Bijlage niet gevonden.',
        'flash.attachment_missing' => 'Het bestand ontbreekt op de server.',
        'flash.session_expired' => 'Je sessie is verlopen. Ververs de pagina en probeer het opnieuw.',
        'session.expired_popup' => 'Je sessie is verlopen. Sla je tekst lokaal op en ververs de pagina om opnieuw in te loggen.',
        'session.auto_refresh_in' => 'Automatisch verversen over %d seconden.',
        'flash.db_open_error' => 'De database kon niet worden geopend: %s',
        'flash.ticket_title_required' => 'Vul een titel in voor het ticket.',
        'flash.invalid_category' => 'Kies een geldige categorie.',
        'flash.description_required' => 'Vul een beschrijving in.',
        'flash.blocked_inconsistent' => 'Je kunt alleen aangeven dat je niet verder kunt werken als werkzaamheden al belemmerd zijn.',
        'flash.invalid_email' => 'Vul een geldig e-mailadres in bij Gebruiker.',
        'flash.invalid_email_list' => 'Een of meer e-mailadressen zijn ongeldig: %s',
        'flash.ticket_created' => 'Ticket #%d is aangemaakt en automatisch toegewezen.',
        'flash.template_ticket_created' => 'Template-ticket #%d is aangemaakt.',
        'flash.template_name_required' => 'Vul een naam in voor het template-fragment.',
        'flash.template_body_required' => 'Vul tekst in voor het template-fragment.',
        'flash.template_created' => 'Template-fragment aangemaakt.',
        'flash.template_updated' => 'Template-fragment bijgewerkt.',
        'flash.template_deleted' => 'Template-fragment verwijderd.',
        'flash.template_not_found' => 'Template-fragment niet gevonden.',
        'flash.template_due_date_required' => 'Due-date is verplicht.',
        'flash.template_due_date_past' => 'De due-date mag niet in het verleden liggen.',
        'flash.template_selection_required' => 'Selecteer minimaal 1 template-fragment.',
        'flash.template_description_required' => 'De template-selectie heeft geen bruikbare tekst opgeleverd.',
        'flash.ticket_participant_add_none' => 'Er zijn geen nieuwe gebruikers toegevoegd.',
        'flash.ticket_participant_added' => '%d gebruiker(s) toegevoegd aan het ticket.',
        'flash.ticket_participant_removed' => 'Gebruiker verwijderd van het ticket.',
        'flash.ticket_participants_saved' => 'Gebruikerswijzigingen opgeslagen.',
        'flash.ticket_participant_remove_requester' => 'De oorspronkelijke aanvrager kan niet worden verwijderd.',
        'flash.ticket_participant_minimum' => 'Er moet minimaal 1 gebruiker op het ticket blijven.',
        'flash.ticket_participant_remove_failed' => 'Gebruiker kon niet van het ticket worden verwijderd.',
        'flash.ticket_not_found' => 'Ticket niet gevonden of niet toegankelijk.',
        'flash.invalid_status' => 'Kies een geldige status.',
        'flash.invalid_employee' => 'Kies een geldige ICT-medewerker.',
        'flash.self_assignment_not_allowed' => 'Een ticket kan niet handmatig worden toegewezen aan de aanvrager.',
        'flash.employee_away' => 'Deze ICT-medewerker staat als afwezig gemarkeerd en kan geen nieuwe tickets ontvangen.',
        'flash.invalid_priority' => 'Kies een geldige prioriteit.',
        'flash.reply_empty' => 'Voeg een bericht, bijlage of statuswijziging toe.',
        'flash.ticket_updated' => 'Ticket #%d is bijgewerkt.',
        'flash.settings_admin_only' => 'Alleen admins kunnen instellingen aanpassen.',
        'flash.settings_saved' => 'De categorie-instellingen en afwezigheid voor ICT zijn opgeslagen.',
        'flash.unknown_action' => 'Onbekende actie ontvangen.',
        'flash.db_error_prefix' => 'Databasefout:',

        // Ticketstatus-weergavelabels (DB-sleutel → vertaalde weergave)
        'status.ingediend' => 'ingediend',
        'status.in_behandeling' => 'in behandeling',
        'status.afwachtende_op_gebruiker' => 'afwachtende op gebruiker',
        'status.afwachtende_op_bestelling' => 'afwachtende op bestelling',
        'status.afgehandeld' => 'afgehandeld',

        // Categorieweergavelabels (DB-sleutel → vertaalde weergave)
        'category.hardware_bestellen' => 'hardware bestellen',
        'category.software_bestellen' => 'software bestellen',
        'category.licentie_aanvragen' => 'licentie aanvragen',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'Hardwareproblemen',
        'category.softwareproblemen' => 'Softwareproblemen',
        'category.web_app_problemen' => 'sleutels.kvt.nl web-applicatieproblemen',
        'category.anders' => 'Anders',
        'category.laptop_klaarmaken' => 'Laptop Klaarmaken',
        'category.telefoon_klaarmaken' => 'Telefoon Klaarmaken',

        // Prioriteitslabels (zonder getal-prefix; voor formatPriorityLabel)
        'priority.label.0' => 'Normaal',
        'priority.label.1' => 'Belemmerd',
        'priority.label.2' => 'Geblokkeerd',

        // Tijdseenheden voor formatDurationSeconds
        'duration.year' => 'jaar',
        'duration.years' => 'jaar',
        'duration.month' => 'maand',
        'duration.months' => 'maanden',
        'duration.week' => 'week',
        'duration.weeks' => 'weken',
        'duration.day' => 'dag',
        'duration.days' => 'dagen',
        'duration.hour' => 'uur',
        'duration.hours' => 'uur',
        'duration.minute' => 'minuut',
        'duration.minutes' => 'minuten',
        'duration.less_than_minute' => 'minder dan 1 minuut',

        // Diverse helpers
        'datetime.unknown' => 'Onbekend',
        'flash.status_changed_to' => 'Status gewijzigd naar %s.',
        'flash.attachment_upload_error' => 'Bijlage "%s" kon niet worden geüpload.',
        'flash.attachment_too_large' => 'Bijlage "%s" is groter dan 20 MB.',

        // E-mail notificaties
        'email.subject_new_ticket' => 'Nieuw ticket #%d',
        'email.subject_created' => 'Ticket #%d is aangemaakt',
        'email.subject_update' => 'Update op ticket #%d',
        'email.subject_assigned' => 'Ticket #%d is aan jou toegewezen',
        'email.subject_user_reply' => 'Reactie van gebruiker op ticket #%d',
        'email.subject_escalation' => 'Escalatie ticket #%d',
        'email.subject_participant_added' => 'Je bent toegevoegd aan ticket #%d',
        'email.intro_new_ict' => 'Er is een nieuw ICT-ticket ingediend.',
        'email.intro_created_self' => 'Je ticket is ontvangen door ICT.',
        'email.intro_created_other' => 'Er is een ticket namens u aangemaakt.',
        'email.intro_update' => 'ICT heeft je ticket bijgewerkt%s',
        'email.intro_update_status' => ' en de status aangepast.',
        'email.intro_update_no_status' => '.',
        'email.intro_assigned' => 'Een ICT-ticket is opnieuw aan jou toegewezen.',
        'email.intro_user_reply' => 'De aanvrager heeft gereageerd op een ticket.',
        'email.intro_escalation' => 'Ticket staat lange tijd onbeantwoord open.',
        'email.intro_participant_added' => 'Je bent als gebruiker toegevoegd aan dit ticket.',
        'email.btn_view' => 'Ticket bekijken',
        'email.field_category' => 'Categorie',
        'email.field_requester' => 'Aanvrager',
        'email.field_assigned' => 'Toegewezen aan',
        'email.field_status' => 'Status',
        'email.field_updated' => 'Bijgewerkt',
        'email.not_assigned' => 'Nog niet toegewezen',
    ],

    /* ------------------------------------------------------------------ */
    'en' => [
        // Header
        'header.title' => 'ICT ticket system',
        'header.subtitle_admin' => 'Manage all tickets, handle replies and distribute work across ICT.',
        'header.subtitle_user' => 'Easily create an ICT ticket and track your reports.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'New ticket',
        'nav.ict_overview' => 'ICT overview',
        'nav.settings' => 'Settings',
        'nav.ict_stats' => 'ICT stats',
        'nav.template_tickets' => 'Template tickets',

        // Ticket list
        'tickets.heading_admin' => 'ICT ticket overview',
        'tickets.heading_user' => 'My tickets',
        'filter.status_label' => 'Status filter',
        'filter.category_label' => 'Category filter',
        'filter.search_label' => 'Search',
        'filter.search_placeholder' => 'Search by ticket number, email, name, text, or date',
        'filter.ict_employee' => 'ICT employee',
        'filter.all_assigned' => 'All assigned',
        'filter.unassigned' => 'Not yet assigned',
        'filter.reset' => 'Reset filters',
        'tickets.empty_admin' => 'There are no tickets matching these filters yet.',
        'tickets.empty_user' => 'You have no tickets yet.',
        'ticket.messages_count' => 'messages',
        'ticket.time_open' => 'time open',
        'ticket.meta_created' => 'Created at · Time open',
        'ticket.meta_updated' => 'Last updated',
        'ticket.meta_due_date' => 'Due date',
        'ticket.meta_priority' => 'Priority',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Impeded',
        'ticket.priority_2' => '2 · Blocked',
        'ticket.messages_heading' => 'Messages',
        'ticket.thread_loading' => 'Loading messages…',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'User',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Assign to',
        'ticket.participants_title' => 'Users on this ticket',
        'ticket.participants_admin_heading' => 'Manage users',
        'ticket.participant_creator' => 'Created by',
        'ticket.participant_remove' => 'Remove',
        'ticket.participants_add_label' => 'Add users',
        'ticket.participants_add_placeholder' => 'Type email addresses, separated by commas',
        'ticket.participants_add_button' => 'Add users',
        'ticket.participants_save_button' => 'Save',
        'ticket.manage_participants_button' => 'Manage users',
        'ticket.participant_remove_confirm' => 'Do you want to mark %s for removal?',
        'ticket.participant_note_added' => 'Users added: %s',
        'ticket.participant_note_removed' => 'Users removed: %s',
        'ticket.unassigned' => 'Not yet assigned',
        'ticket.new_message' => 'New message',
        'ticket.new_message_placeholder' => 'Type an update or additional information here.',
        'ticket.key_picker_tooltip' => 'Insert keyboard shortcuts',
        'ticket.emoji_picker_tooltip' => 'Insert emoji',
        'ticket.reopen' => 'Reopen ticket',
        'ticket.add_attachments' => 'Add attachments',
        'ticket.preview_image' => 'Enlarge image',
        'ticket.preview_file' => 'Preview file',
        'ticket.preview_close' => 'Close preview',
        'ticket.file_hint' => 'Maximum 20 MB per file.',
        'ticket.btn_save' => 'Save',
        'ticket.btn_reply' => 'Post reply and email ICT',
        'ticket.show_original' => 'Show original',
        'ticket.show_translation' => 'Show translation',
        'translation.loading_tooltip' => 'Translation is loading',
        'translation.error_tooltip' => 'Translation failed. Click for details.',
        'translation.error_title' => 'Translation Error',
        'translation.error_fallback' => 'An error occurred while loading the translation.',

        // New ticket form
        'new_ticket.heading' => 'Create new ticket',
        'new_ticket.intro' => 'A ticket is automatically assigned to an ICT employee based on category and current workload.',
        'new_ticket.title_label' => 'Title',
        'new_ticket.title_placeholder' => 'For example: New scanner needed',
        'new_ticket.category_label' => 'Category',
        'new_ticket.category_option' => 'Choose a category',
        'new_ticket.description_label' => 'Description',
        'new_ticket.description_placeholder' => 'Describe the problem or request as clearly as possible.',
        'new_ticket.blocked' => 'My work is being impeded',
        'new_ticket.fully_blocked' => 'I cannot continue working until this is resolved',
        'new_ticket.requester_label' => 'User',
        'new_ticket.requester_list_label' => 'Users (first address is requester)',
        'new_ticket.requester_placeholder' => 'name@kvt.nl (optional, to create a ticket on behalf of someone else)',
        'new_ticket.requester_hint' => 'ICT only: this e-mail address will be used as the requester if filled in.',
        'new_ticket.requester_list_hint' => 'ICT: enter one or more email addresses.',
        'new_ticket.participants_label' => 'Additional users',
        'new_ticket.participants_placeholder' => 'name1@kvt.nl, name2@kvt.nl',
        'new_ticket.participants_hint' => 'Add colleagues who should also see this ticket under My tickets.',
        'new_ticket.attachments_label' => 'Screenshots or documents',
        'new_ticket.btn_submit' => 'Submit ticket',

        // Template tickets
        'template_ticket.heading' => 'Create template ticket',
        'template_ticket.intro' => 'Create a ticket from template fragments and choose a template category.',
        'template_ticket.category_label' => 'Template category',
        'template_ticket.assignee_label' => 'Assignment',
        'template_ticket.assignee_auto' => 'Auto',
        'template_ticket.due_date_label' => 'Due date',
        'template_ticket.title_label' => 'Ticket title',
        'template_ticket.title_placeholder' => 'For example: Prepare laptop for new employee',
        'template_ticket.preview_label' => 'Ticket preview',
        'template_ticket.preview_hint' => 'Preview equals the final ticket description (template texts joined with newlines).',
        'template_ticket.create_button' => 'Create template ticket',
        'template_ticket.templates_heading' => 'Template fragments',
        'template_ticket.create_template_heading' => 'Create template',
        'template_ticket.edit_heading' => 'Edit template',
        'template_ticket.template_name_label' => 'Name',
        'template_ticket.template_name_placeholder' => 'For example: New user setup',
        'template_ticket.template_body_label' => 'Text',
        'template_ticket.template_body_placeholder' => 'Type the template fragment here.',
        'template_ticket.create_template_button' => 'Save template',
        'template_ticket.save_template_button' => 'Save changes',
        'template_ticket.delete_template_button' => 'Delete template',
        'template_ticket.edit_template_button' => 'Edit',
        'template_ticket.new_template_button' => 'New template',
        'template_ticket.modal_close' => 'Close',
        'template_ticket.back_to_list' => 'Back to list',
        'template_ticket.delete_confirm' => 'Are you sure you want to delete this template fragment?',
        'template_ticket.empty_templates' => 'There are no template fragments yet.',
        'template_ticket.select_template_error' => 'Select at least 1 template fragment.',

        // Settings
        'settings.heading' => 'Settings per ICT user',
        'settings.intro' => 'Enable or disable categories per ICT colleague and mark employees as absent. New tickets are automatically assigned to the least busy available colleague.',
        'settings.regular_categories_heading' => 'Regular ticket categories',
        'settings.template_categories_heading' => 'Template ticket categories',
        'settings.col_user' => 'ICT user',
        'settings.col_open_tickets' => 'Open tickets',
        'settings.btn_save' => 'Save settings',
        'settings.db_exists' => 'exists',
        'settings.db_missing' => 'missing',
        'settings.dir_writable' => 'directory writable',
        'settings.file_writable' => 'file writable',
        'settings.yes' => 'yes',
        'settings.no' => 'no',

        // Statistics
        'stats.heading' => 'ICT statistics',
        'stats.intro' => 'View totals, performance per ICT employee and waiting times per regular user. For resolved tickets we measure from <strong>created</strong> to <strong>resolved</strong>; open tickets count up to <strong>now</strong>.',
        'stats.total_tickets' => 'Total tickets',
        'stats.open_tickets' => 'Open tickets',
        'stats.resolved_tickets' => 'Resolved tickets',
        'stats.waiting_order' => 'Waiting for order',
        'stats.per_ict' => 'Per ICT employee',
        'stats.col_ict_employee' => 'ICT employee',
        'stats.col_handled' => 'Resolved',
        'stats.col_avg_open' => 'Average time open',
        'stats.col_max_open' => 'Longest open time',
        'stats.col_outstanding' => 'Outstanding',
        'stats.col_waiting_order' => 'Waiting for order',
        'stats.per_user' => 'Per regular user',
        'stats.no_user_stats' => 'No statistics for regular users are available yet.',
        'stats.col_user' => 'User',
        'stats.col_submitted' => 'Tickets submitted',
        'stats.col_avg_wait' => 'Average wait time',
        'stats.col_max_wait' => 'Longest wait time',
        'stats.col_avg_response' => 'Average response time',
        'stats.wait_note' => '* Wait time only includes time in <strong>submitted</strong>, <strong>in progress</strong> and <strong>awaiting order</strong>. Time in <strong>resolved</strong> and <strong>awaiting user</strong> is excluded. Average response time is the average time in <strong>awaiting user</strong>.',
        'stats.sidebar_heading' => 'Open tickets',
        'stats.sidebar_empty' => 'No open tickets.',
        'stats.no_assigned' => 'Not assigned',
        'bs.card_changed' => '#%d changed',
        'bs.card_status' => 'Status: %s',
        'bs.card_assigned' => 'Assigned to: %s',
        'bs.card_unassigned' => 'Nobody',
        'bs.card_new_message' => 'New message',
        'bs.no_user_stats' => 'No statistics available for regular users yet.',
        'bs.col_user' => 'User',
        'bs.col_submitted' => 'Tickets submitted',
        'bs.col_avg_wait' => 'Average wait time',
        'bs.col_max_wait' => 'Longest wait time',
        'bs.col_avg_response' => 'Average response time',
        'bs.wait_note' => '* Wait time only includes time in <strong>submitted</strong>, <strong>in progress</strong> and <strong>awaiting order</strong>. Time in <strong>resolved</strong> and <strong>awaiting user</strong> is excluded. Average response time is the average time in <strong>awaiting user</strong>.',
        'bs.new_ticket_from' => 'New ticket from %s!',
        'bs.assigned_to' => 'Assigned to: %s',
        'bs.not_yet_assigned' => 'Not yet assigned',

        // Flash messages / errors
        'flash.admin_only' => 'Only ICT users have access to the ticket overview.',
        'flash.attachment_not_found' => 'Attachment not found.',
        'flash.attachment_missing' => 'The file is missing on the server.',
        'flash.session_expired' => 'Your session has expired. Please refresh the page and try again.',
        'session.expired_popup' => 'Your session has expired. Save your text locally and refresh the page to sign in again.',
        'session.auto_refresh_in' => 'Automatically refreshing in %d seconds.',
        'flash.db_open_error' => 'The database could not be opened: %s',
        'flash.ticket_title_required' => 'Please enter a title for the ticket.',
        'flash.invalid_category' => 'Please choose a valid category.',
        'flash.description_required' => 'Please enter a description.',
        'flash.blocked_inconsistent' => 'You can only indicate that you cannot continue working if your work is already impeded.',
        'flash.invalid_email' => 'Please enter a valid e-mail address in the User field.',
        'flash.invalid_email_list' => 'One or more e-mail addresses are invalid: %s',
        'flash.ticket_created' => 'Ticket #%d has been created and automatically assigned.',
        'flash.template_ticket_created' => 'Template ticket #%d has been created.',
        'flash.template_name_required' => 'Please enter a name for the template fragment.',
        'flash.template_body_required' => 'Please enter text for the template fragment.',
        'flash.template_created' => 'Template fragment created.',
        'flash.template_updated' => 'Template fragment updated.',
        'flash.template_deleted' => 'Template fragment deleted.',
        'flash.template_not_found' => 'Template fragment not found.',
        'flash.template_due_date_required' => 'Due date is required.',
        'flash.template_due_date_past' => 'Due date cannot be in the past.',
        'flash.template_selection_required' => 'Select at least 1 template fragment.',
        'flash.template_description_required' => 'The selected templates did not produce usable text.',
        'flash.ticket_participant_add_none' => 'No new users were added.',
        'flash.ticket_participant_added' => '%d user(s) added to the ticket.',
        'flash.ticket_participant_removed' => 'User removed from the ticket.',
        'flash.ticket_participants_saved' => 'Participant changes saved.',
        'flash.ticket_participant_remove_requester' => 'The original requester cannot be removed.',
        'flash.ticket_participant_minimum' => 'At least 1 user must remain on the ticket.',
        'flash.ticket_participant_remove_failed' => 'The user could not be removed from the ticket.',
        'flash.ticket_not_found' => 'Ticket not found or not accessible.',
        'flash.invalid_status' => 'Please choose a valid status.',
        'flash.invalid_employee' => 'Please choose a valid ICT employee.',
        'flash.self_assignment_not_allowed' => 'A ticket cannot be manually assigned to its requester.',
        'flash.employee_away' => 'This ICT employee is marked as absent and cannot receive new tickets.',
        'flash.invalid_priority' => 'Please choose a valid priority.',
        'flash.reply_empty' => 'Please add a message, attachment or status change.',
        'flash.ticket_updated' => 'Ticket #%d has been updated.',
        'flash.settings_admin_only' => 'Only admins can change settings.',
        'flash.settings_saved' => 'Category settings and ICT absences have been saved.',
        'flash.unknown_action' => 'Unknown action received.',
        'flash.db_error_prefix' => 'Database error:',

        // Ticket status display labels
        'status.ingediend' => 'submitted',
        'status.in_behandeling' => 'in progress',
        'status.afwachtende_op_gebruiker' => 'awaiting user',
        'status.afwachtende_op_bestelling' => 'awaiting order',
        'status.afgehandeld' => 'resolved',

        // Category display labels
        'category.hardware_bestellen' => 'order hardware',
        'category.software_bestellen' => 'order software',
        'category.licentie_aanvragen' => 'request license',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'hardware problems',
        'category.softwareproblemen' => 'software problems',
        'category.web_app_problemen' => 'sleutels.kvt.nl web application problems',
        'category.anders' => 'Other',
        'category.laptop_klaarmaken' => 'Prepare laptop',
        'category.telefoon_klaarmaken' => 'Prepare phone',

        // Priority labels (without number prefix)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Impeded',
        'priority.label.2' => 'Blocked',

        // Duration units for formatDurationSeconds
        'duration.year' => 'year',
        'duration.years' => 'years',
        'duration.month' => 'month',
        'duration.months' => 'months',
        'duration.week' => 'week',
        'duration.weeks' => 'weeks',
        'duration.day' => 'day',
        'duration.days' => 'days',
        'duration.hour' => 'hour',
        'duration.hours' => 'hours',
        'duration.minute' => 'minute',
        'duration.minutes' => 'minutes',
        'duration.less_than_minute' => 'less than 1 minute',

        // Misc helpers
        'datetime.unknown' => 'Unknown',
        'flash.status_changed_to' => 'Status changed to %s.',
        'flash.attachment_upload_error' => 'Attachment "%s" could not be uploaded.',
        'flash.attachment_too_large' => 'Attachment "%s" is larger than 20 MB.',

        // Email notifications
        'email.subject_new_ticket' => 'New ticket #%d',
        'email.subject_created' => 'Ticket #%d has been created',
        'email.subject_update' => 'Update on ticket #%d',
        'email.subject_assigned' => 'Ticket #%d has been assigned to you',
        'email.subject_user_reply' => 'User reply on ticket #%d',
        'email.subject_escalation' => 'Escalation ticket #%d',
        'email.subject_participant_added' => 'You were added to ticket #%d',
        'email.intro_new_ict' => 'A new ICT ticket has been submitted.',
        'email.intro_created_self' => 'Your ticket has been received by ICT.',
        'email.intro_created_other' => 'A ticket has been created on your behalf.',
        'email.intro_update' => 'ICT has updated your ticket%s',
        'email.intro_update_status' => ' and changed the status.',
        'email.intro_update_no_status' => '.',
        'email.intro_assigned' => 'An ICT ticket has been reassigned to you.',
        'email.intro_user_reply' => 'The requester has replied to a ticket.',
        'email.intro_escalation' => 'Ticket has been open without a response for a long time.',
        'email.intro_participant_added' => 'You were added as a user on this ticket.',
        'email.btn_view' => 'View ticket',
        'email.field_category' => 'Category',
        'email.field_requester' => 'Requester',
        'email.field_assigned' => 'Assigned to',
        'email.field_status' => 'Status',
        'email.field_updated' => 'Updated',
        'email.not_assigned' => 'Not yet assigned',
    ],

    /* ------------------------------------------------------------------ */
    'de' => [
        // Header
        'header.title' => 'ICT-Ticketsystem',
        'header.subtitle_admin' => 'Verwalten Sie alle Tickets, bearbeiten Sie Antworten und verteilen Sie Aufgaben effizient im ICT-Team.',
        'header.subtitle_user' => 'Erstellen Sie ganz einfach ein ICT-Ticket und verfolgen Sie Ihre Meldungen.',
        'header.admin_suffix' => ' · Admin',
        'nav.new_ticket' => 'Neues Ticket',
        'nav.ict_overview' => 'ICT-Übersicht',
        'nav.settings' => 'Einstellungen',
        'nav.ict_stats' => 'ICT-Statistiken',
        'nav.template_tickets' => 'Template-Tickets',

        // Ticket list
        'tickets.heading_admin' => 'ICT-Ticketübersicht',
        'tickets.heading_user' => 'Meine Tickets',
        'filter.status_label' => 'Statusfilter',
        'filter.category_label' => 'Kategoriefilter',
        'filter.search_label' => 'Suche',
        'filter.search_placeholder' => 'Nach Ticketnummer, E-Mail, Name, Text oder Datum suchen',
        'filter.ict_employee' => 'ICT-Mitarbeiter',
        'filter.all_assigned' => 'Alle zugewiesen',
        'filter.unassigned' => 'Noch nicht zugewiesen',
        'filter.reset' => 'Filter zurücksetzen',
        'tickets.empty_admin' => 'Es gibt noch keine Tickets, die diesen Filtern entsprechen.',
        'tickets.empty_user' => 'Sie haben noch keine Tickets.',
        'ticket.messages_count' => 'Nachrichten',
        'ticket.time_open' => 'Offen seit',
        'ticket.meta_created' => 'Erstellt am · Offen seit',
        'ticket.meta_updated' => 'Zuletzt aktualisiert',
        'ticket.meta_due_date' => 'Fälligkeitsdatum',
        'ticket.meta_priority' => 'Priorität',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Beeinträchtigt',
        'ticket.priority_2' => '2 · Blockiert',
        'ticket.messages_heading' => 'Nachrichten',
        'ticket.thread_loading' => 'Nachrichten werden geladen…',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Benutzer',
        'ticket.status_label' => 'Status',
        'ticket.assigned_to' => 'Zuweisen an',
        'ticket.participants_title' => 'Benutzer in diesem Ticket',
        'ticket.participants_admin_heading' => 'Benutzer verwalten',
        'ticket.participant_creator' => 'Erstellt von',
        'ticket.participant_remove' => 'Entfernen',
        'ticket.participants_add_label' => 'Benutzer hinzufügen',
        'ticket.participants_add_placeholder' => 'E-Mail-Adressen eingeben, durch Kommas getrennt',
        'ticket.participants_add_button' => 'Benutzer hinzufügen',
        'ticket.participants_save_button' => 'Speichern',
        'ticket.manage_participants_button' => 'Benutzer verwalten',
        'ticket.participant_remove_confirm' => 'Möchten Sie %s zum Entfernen markieren?',
        'ticket.participant_note_added' => 'Benutzer hinzugefugt: %s',
        'ticket.participant_note_removed' => 'Benutzer entfernt: %s',
        'ticket.unassigned' => 'Noch nicht zugewiesen',
        'ticket.new_message' => 'Neue Nachricht',
        'ticket.new_message_placeholder' => 'Geben Sie hier eine Aktualisierung oder zusätzliche Informationen ein.',
        'ticket.key_picker_tooltip' => 'Tastaturkürzel einfügen',
        'ticket.emoji_picker_tooltip' => 'Emoji einfügen',
        'ticket.reopen' => 'Ticket wieder öffnen',
        'ticket.add_attachments' => 'Anhänge hinzufügen',
        'ticket.preview_image' => 'Bild vergrößern',
        'ticket.preview_file' => 'Datei anzeigen',
        'ticket.preview_close' => 'Vorschau schließen',
        'ticket.file_hint' => 'Maximal 20 MB pro Datei.',
        'ticket.btn_save' => 'Speichern',
        'ticket.btn_reply' => 'Antwort senden und ICT benachrichtigen',
        'ticket.show_original' => 'Original anzeigen',
        'ticket.show_translation' => 'Uebersetzung anzeigen',
        'translation.loading_tooltip' => 'Uebersetzung wird geladen',
        'translation.error_tooltip' => 'Uebersetzung fehlgeschlagen. Fuer Details klicken.',
        'translation.error_title' => 'Uebersetzungsfehler',
        'translation.error_fallback' => 'Beim Laden der Uebersetzung ist ein Fehler aufgetreten.',

        // New ticket form
        'new_ticket.heading' => 'Neues Ticket erstellen',
        'new_ticket.intro' => 'Ein Ticket wird automatisch einem ICT-Mitarbeiter zugewiesen, basierend auf Kategorie und aktueller Arbeitsbelastung.',
        'new_ticket.title_label' => 'Titel',
        'new_ticket.title_placeholder' => 'Zum Beispiel: Neuer Scanner benötigt',
        'new_ticket.category_label' => 'Kategorie',
        'new_ticket.category_option' => 'Kategorie wählen',
        'new_ticket.description_label' => 'Beschreibung',
        'new_ticket.description_placeholder' => 'Beschreiben Sie das Problem oder die Anfrage so genau wie möglich.',
        'new_ticket.blocked' => 'Meine Arbeit wird beeinträchtigt',
        'new_ticket.fully_blocked' => 'Ich kann nicht weiterarbeiten, bis dies gelöst ist',
        'new_ticket.requester_label' => 'Benutzer',
        'new_ticket.requester_list_label' => 'Benutzer (erste Adresse ist der Anfragende)',
        'new_ticket.requester_placeholder' => 'name@kvt.nl (optional, um ein Ticket im Namen einer anderen Person zu erstellen)',
        'new_ticket.requester_hint' => 'Nur für ICT: Diese E-Mail-Adresse wird als Anfrager verwendet, wenn sie ausgefüllt ist.',
        'new_ticket.requester_list_hint' => 'ICT: Geben Sie eine oder mehrere E-Mail-Adressen ein.',
        'new_ticket.participants_label' => 'Zusätzliche Benutzer',
        'new_ticket.participants_placeholder' => 'name1@kvt.nl, name2@kvt.nl',
        'new_ticket.participants_hint' => 'Fügen Sie Kollegen hinzu, die dieses Ticket ebenfalls unter Meine Tickets sehen sollen.',
        'new_ticket.attachments_label' => 'Screenshots oder Dokumente',
        'new_ticket.btn_submit' => 'Ticket einreichen',

        // Template tickets
        'template_ticket.heading' => 'Template-Ticket erstellen',
        'template_ticket.intro' => 'Erstellen Sie ein Ticket aus Template-Fragmenten und wählen Sie eine Template-Kategorie.',
        'template_ticket.category_label' => 'Template-Kategorie',
        'template_ticket.assignee_label' => 'Zuweisung',
        'template_ticket.assignee_auto' => 'Auto',
        'template_ticket.due_date_label' => 'Fälligkeitsdatum',
        'template_ticket.title_label' => 'Tickettitel',
        'template_ticket.title_placeholder' => 'Zum Beispiel: Laptop fur neuen Mitarbeiter vorbereiten',
        'template_ticket.preview_label' => 'Ticket-Vorschau',
        'template_ticket.preview_hint' => 'Die Vorschau entspricht der finalen Ticketbeschreibung (Template-Texte mit Zeilenumbrüchen).',
        'template_ticket.create_button' => 'Template-Ticket erstellen',
        'template_ticket.templates_heading' => 'Template-Fragmente',
        'template_ticket.create_template_heading' => 'Template erstellen',
        'template_ticket.edit_heading' => 'Template bearbeiten',
        'template_ticket.template_name_label' => 'Name',
        'template_ticket.template_name_placeholder' => 'Zum Beispiel: Neues Benutzer-Setup',
        'template_ticket.template_body_label' => 'Text',
        'template_ticket.template_body_placeholder' => 'Geben Sie hier das Template-Fragment ein.',
        'template_ticket.create_template_button' => 'Template speichern',
        'template_ticket.save_template_button' => 'Änderungen speichern',
        'template_ticket.delete_template_button' => 'Template löschen',
        'template_ticket.edit_template_button' => 'Bearbeiten',
        'template_ticket.new_template_button' => 'Neues Template',
        'template_ticket.modal_close' => 'Schließen',
        'template_ticket.back_to_list' => 'Zurück zur Liste',
        'template_ticket.delete_confirm' => 'Möchten Sie dieses Template-Fragment wirklich löschen?',
        'template_ticket.empty_templates' => 'Es sind noch keine Template-Fragmente vorhanden.',
        'template_ticket.select_template_error' => 'Wählen Sie mindestens 1 Template-Fragment aus.',

        // Settings
        'settings.heading' => 'Einstellungen pro ICT-Benutzer',
        'settings.intro' => 'Aktivieren oder deaktivieren Sie Kategorien pro ICT-Kollegen und markieren Sie Mitarbeiter als abwesend. Neue Tickets werden automatisch dem am wenigsten ausgelasteten verfügbaren Kollegen zugewiesen.',
        'settings.regular_categories_heading' => 'Reguläre Ticketkategorien',
        'settings.template_categories_heading' => 'Template-Ticketkategorien',
        'settings.col_user' => 'ICT-Benutzer',
        'settings.col_open_tickets' => 'Offene Tickets',
        'settings.btn_save' => 'Einstellungen speichern',
        'settings.db_exists' => 'vorhanden',
        'settings.db_missing' => 'fehlt',
        'settings.dir_writable' => 'Verzeichnis beschreibbar',
        'settings.file_writable' => 'Datei beschreibbar',
        'settings.yes' => 'ja',
        'settings.no' => 'nein',

        // Statistics
        'stats.heading' => 'ICT-Statistiken',
        'stats.intro' => 'Hier sehen Sie die Gesamtzahlen, Leistungen pro ICT-Mitarbeiter und Wartezeiten pro Benutzer. Bei erledigten Tickets messen wir von <strong>erstellt</strong> bis <strong>erledigt</strong>; offene Tickets zählen bis <strong>jetzt</strong>.',
        'stats.total_tickets' => 'Tickets insgesamt',
        'stats.open_tickets' => 'Offene Tickets',
        'stats.resolved_tickets' => 'Erledigte Tickets',
        'stats.waiting_order' => 'Wartet auf Bestellung',
        'stats.per_ict' => 'Pro ICT-Mitarbeiter',
        'stats.col_ict_employee' => 'ICT-Mitarbeiter',
        'stats.col_handled' => 'Erledigt',
        'stats.col_avg_open' => 'Durchschnittliche Offenzeit',
        'stats.col_max_open' => 'Längste Offenzeit',
        'stats.col_outstanding' => 'Ausstehend',
        'stats.col_waiting_order' => 'Wartet auf Bestellung',
        'stats.per_user' => 'Pro normalen Benutzer',
        'stats.no_user_stats' => 'Es sind noch keine Statistiken für normale Benutzer verfügbar.',
        'stats.col_user' => 'Benutzer',
        'stats.col_submitted' => 'Eingereichte Tickets',
        'stats.col_avg_wait' => 'Durchschnittliche Wartezeit',
        'stats.col_max_wait' => 'Längste Wartezeit',
        'stats.col_avg_response' => 'Durchschnittliche Reaktionszeit',
        'stats.wait_note' => '* Die Wartezeit enthält nur die Zeit in den Status <strong>eingereicht</strong>, <strong>in Bearbeitung</strong> und <strong>wartet auf Bestellung</strong>. Zeit in <strong>erledigt</strong> und <strong>wartet auf Benutzer</strong> wird nicht mitgezählt. Die durchschnittliche Reaktionszeit ist die durchschnittliche Zeit in <strong>wartet auf Benutzer</strong>.',
        'stats.sidebar_heading' => 'Offene Tickets',
        'stats.sidebar_empty' => 'Keine offenen Tickets.',
        'stats.no_assigned' => 'Nicht zugewiesen',
        'bs.card_changed' => '#%d geändert',
        'bs.card_status' => 'Status: %s',
        'bs.card_assigned' => 'Zugewiesen an: %s',
        'bs.card_unassigned' => 'Niemand',
        'bs.card_new_message' => 'Neue Nachricht',
        'bs.no_user_stats' => 'Noch keine Statistiken für normale Benutzer verfügbar.',
        'bs.col_user' => 'Benutzer',
        'bs.col_submitted' => 'Tickets eingereicht',
        'bs.col_avg_wait' => 'Durchschnittliche Wartezeit',
        'bs.col_max_wait' => 'Längste Wartezeit',
        'bs.col_avg_response' => 'Durchschnittliche Reaktionszeit',
        'bs.wait_note' => '* Die Wartezeit enthält nur die Zeit in den Status <strong>eingereicht</strong>, <strong>in Bearbeitung</strong> und <strong>wartet auf Bestellung</strong>. Zeit in <strong>erledigt</strong> und <strong>wartet auf Benutzer</strong> wird nicht mitgezählt. Die durchschnittliche Reaktionszeit ist die durchschnittliche Zeit in <strong>wartet auf Benutzer</strong>.',
        'bs.new_ticket_from' => 'Neues Ticket von %s!',
        'bs.assigned_to' => 'Zugewiesen an: %s',
        'bs.not_yet_assigned' => 'Noch nicht zugewiesen',

        // Flash messages / errors
        'flash.admin_only' => 'Nur ICT-Benutzer haben Zugriff auf die Ticketübersicht.',
        'flash.attachment_not_found' => 'Anhang nicht gefunden.',
        'flash.attachment_missing' => 'Die Datei fehlt auf dem Server.',
        'flash.session_expired' => 'Ihre Sitzung ist abgelaufen. Bitte laden Sie die Seite neu und versuchen Sie es erneut.',
        'session.expired_popup' => 'Ihre Sitzung ist abgelaufen. Speichern Sie Ihren Text lokal und laden Sie die Seite neu, um sich erneut anzumelden.',
        'session.auto_refresh_in' => 'Automatische Aktualisierung in %d Sekunden.',
        'flash.db_open_error' => 'Die Datenbank konnte nicht geöffnet werden: %s',
        'flash.ticket_title_required' => 'Bitte geben Sie einen Titel für das Ticket ein.',
        'flash.invalid_category' => 'Bitte wählen Sie eine gültige Kategorie.',
        'flash.description_required' => 'Bitte geben Sie eine Beschreibung ein.',
        'flash.blocked_inconsistent' => 'Sie können nur angeben, dass Sie nicht weiterarbeiten können, wenn Ihre Arbeit bereits beeinträchtigt ist.',
        'flash.invalid_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse im Feld Benutzer ein.',
        'flash.invalid_email_list' => 'Eine oder mehrere E-Mail-Adressen sind ungültig: %s',
        'flash.ticket_created' => 'Ticket #%d wurde erstellt und automatisch zugewiesen.',
        'flash.template_ticket_created' => 'Template-Ticket #%d wurde erstellt.',
        'flash.template_name_required' => 'Bitte geben Sie einen Namen für das Template-Fragment ein.',
        'flash.template_body_required' => 'Bitte geben Sie Text für das Template-Fragment ein.',
        'flash.template_created' => 'Template-Fragment erstellt.',
        'flash.template_updated' => 'Template-Fragment aktualisiert.',
        'flash.template_deleted' => 'Template-Fragment gelöscht.',
        'flash.template_not_found' => 'Template-Fragment nicht gefunden.',
        'flash.template_due_date_required' => 'Ein Fälligkeitsdatum ist erforderlich.',
        'flash.template_due_date_past' => 'Das Fälligkeitsdatum darf nicht in der Vergangenheit liegen.',
        'flash.template_selection_required' => 'Wählen Sie mindestens 1 Template-Fragment aus.',
        'flash.template_description_required' => 'Die ausgewählten Templates enthalten keinen verwendbaren Text.',
        'flash.ticket_participant_add_none' => 'Es wurden keine neuen Benutzer hinzugefügt.',
        'flash.ticket_participant_added' => '%d Benutzer wurde(n) zum Ticket hinzugefügt.',
        'flash.ticket_participant_removed' => 'Benutzer wurde aus dem Ticket entfernt.',
        'flash.ticket_participants_saved' => 'Benutzeränderungen wurden gespeichert.',
        'flash.ticket_participant_remove_requester' => 'Der ursprüngliche Anfragende kann nicht entfernt werden.',
        'flash.ticket_participant_minimum' => 'Mindestens 1 Benutzer muss im Ticket verbleiben.',
        'flash.ticket_participant_remove_failed' => 'Der Benutzer konnte nicht aus dem Ticket entfernt werden.',
        'flash.ticket_not_found' => 'Ticket nicht gefunden oder nicht zugänglich.',
        'flash.invalid_status' => 'Bitte wählen Sie einen gültigen Status.',
        'flash.invalid_employee' => 'Bitte wählen Sie einen gültigen ICT-Mitarbeiter.',
        'flash.self_assignment_not_allowed' => 'Ein Ticket kann nicht manuell dem Anfragenden zugewiesen werden.',
        'flash.employee_away' => 'Dieser ICT-Mitarbeiter ist als abwesend markiert und kann keine neuen Tickets erhalten.',
        'flash.invalid_priority' => 'Bitte wählen Sie eine gültige Priorität.',
        'flash.reply_empty' => 'Bitte fügen Sie eine Nachricht, einen Anhang oder eine Statusänderung hinzu.',
        'flash.ticket_updated' => 'Ticket #%d wurde aktualisiert.',
        'flash.settings_admin_only' => 'Nur Admins können Einstellungen ändern.',
        'flash.settings_saved' => 'Die Kategorieeinstellungen und ICT-Abwesenheiten wurden gespeichert.',
        'flash.unknown_action' => 'Unbekannte Aktion empfangen.',
        'flash.db_error_prefix' => 'Datenbankfehler:',

        // Ticketstatus-Anzeigebezeichnungen
        'status.ingediend' => 'eingereicht',
        'status.in_behandeling' => 'in Bearbeitung',
        'status.afwachtende_op_gebruiker' => 'wartet auf Benutzer',
        'status.afwachtende_op_bestelling' => 'wartet auf Bestellung',
        'status.afgehandeld' => 'erledigt',

        // Kategorieanzeigebezeichnungen
        'category.hardware_bestellen' => 'Hardware bestellen',
        'category.software_bestellen' => 'Software bestellen',
        'category.licentie_aanvragen' => 'Lizenz anfordern',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'Hardwareprobleme',
        'category.softwareproblemen' => 'Softwareprobleme',
        'category.web_app_problemen' => 'sleutels.kvt.nl Web-Anwendungsprobleme',
        'category.anders' => 'Sonstiges',
        'category.laptop_klaarmaken' => 'Laptop vorbereiten',
        'category.telefoon_klaarmaken' => 'Telefon vorbereiten',

        // Prioritätsbezeichnungen (ohne Zahlenpräfix)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Beeinträchtigt',
        'priority.label.2' => 'Blockiert',

        // Zeiteinheiten für formatDurationSeconds
        'duration.year' => 'Jahr',
        'duration.years' => 'Jahre',
        'duration.month' => 'Monat',
        'duration.months' => 'Monate',
        'duration.week' => 'Woche',
        'duration.weeks' => 'Wochen',
        'duration.day' => 'Tag',
        'duration.days' => 'Tage',
        'duration.hour' => 'Stunde',
        'duration.hours' => 'Stunden',
        'duration.minute' => 'Minute',
        'duration.minutes' => 'Minuten',
        'duration.less_than_minute' => 'weniger als 1 Minute',

        // Sonstiges
        'datetime.unknown' => 'Unbekannt',
        'flash.status_changed_to' => 'Status geändert auf %s.',
        'flash.attachment_upload_error' => 'Anhang "%s" konnte nicht hochgeladen werden.',
        'flash.attachment_too_large' => 'Anhang "%s" ist größer als 20 MB.',

        // E-Mail-Benachrichtigungen
        'email.subject_new_ticket' => 'Neues Ticket #%d',
        'email.subject_created' => 'Ticket #%d wurde erstellt',
        'email.subject_update' => 'Aktualisierung zu Ticket #%d',
        'email.subject_assigned' => 'Ticket #%d wurde Ihnen zugewiesen',
        'email.subject_user_reply' => 'Nutzerantwort auf Ticket #%d',
        'email.subject_escalation' => 'Eskalation Ticket #%d',
        'email.subject_participant_added' => 'Sie wurden zu Ticket #%d hinzugefügt',
        'email.intro_new_ict' => 'Ein neues ICT-Ticket wurde eingereicht.',
        'email.intro_created_self' => 'Ihr Ticket wurde vom ICT-Team empfangen.',
        'email.intro_created_other' => 'Ein Ticket wurde in Ihrem Namen erstellt.',
        'email.intro_update' => 'ICT hat Ihr Ticket aktualisiert%s',
        'email.intro_update_status' => ' und den Status geändert.',
        'email.intro_update_no_status' => '.',
        'email.intro_assigned' => 'Ein ICT-Ticket wurde erneut Ihnen zugewiesen.',
        'email.intro_user_reply' => 'Der Antragsteller hat auf ein Ticket geantwortet.',
        'email.intro_escalation' => 'Das Ticket steht seit langer Zeit ohne Antwort offen.',
        'email.intro_participant_added' => 'Sie wurden als Benutzer zu diesem Ticket hinzugefügt.',
        'email.btn_view' => 'Ticket ansehen',
        'email.field_category' => 'Kategorie',
        'email.field_requester' => 'Antragsteller',
        'email.field_assigned' => 'Zugewiesen an',
        'email.field_status' => 'Status',
        'email.field_updated' => 'Aktualisiert',
        'email.not_assigned' => 'Noch nicht zugewiesen',
    ],

    /* ------------------------------------------------------------------ */
    'fr' => [
        // Header
        'header.title' => 'Système de tickets ICT',
        'header.subtitle_admin' => 'Gérez tous les tickets, traitez les réponses et répartissez le travail efficacement au sein de l\'équipe ICT.',
        'header.subtitle_user' => 'Créez facilement un ticket ICT et suivez vos signalements.',
        'header.admin_suffix' => ' · admin',
        'nav.new_ticket' => 'Nouveau ticket',
        'nav.ict_overview' => 'Vue d\'ensemble ICT',
        'nav.settings' => 'Paramètres',
        'nav.ict_stats' => 'Statistiques ICT',
        'nav.template_tickets' => 'Tickets modèle',

        // Ticket list
        'tickets.heading_admin' => 'Vue d\'ensemble des tickets ICT',
        'tickets.heading_user' => 'Mes tickets',
        'filter.status_label' => 'Filtre par statut',
        'filter.category_label' => 'Filtre par catégorie',
        'filter.search_label' => 'Recherche',
        'filter.search_placeholder' => 'Rechercher par numéro, e-mail, nom, texte ou date',
        'filter.ict_employee' => 'Employé ICT',
        'filter.all_assigned' => 'Tous les assignés',
        'filter.unassigned' => 'Non encore assigné',
        'filter.reset' => 'Réinitialiser les filtres',
        'tickets.empty_admin' => 'Il n\'y a encore aucun ticket correspondant à ces filtres.',
        'tickets.empty_user' => 'Vous n\'avez encore aucun ticket.',
        'ticket.messages_count' => 'messages',
        'ticket.time_open' => 'temps ouvert',
        'ticket.meta_created' => 'Créé le · Temps ouvert',
        'ticket.meta_updated' => 'Dernière mise à jour',
        'ticket.meta_due_date' => 'Date d\'échéance',
        'ticket.meta_priority' => 'Priorité',
        'ticket.priority_0' => '0 · Normal',
        'ticket.priority_1' => '1 · Entravé',
        'ticket.priority_2' => '2 · Bloqué',
        'ticket.messages_heading' => 'Messages',
        'ticket.thread_loading' => 'Loading messages…',
        'ticket.role_admin' => 'ICT',
        'ticket.role_user' => 'Utilisateur',
        'ticket.status_label' => 'Statut',
        'ticket.assigned_to' => 'Assigner à',
        'ticket.participants_title' => 'Utilisateurs de ce ticket',
        'ticket.participants_admin_heading' => 'Gérer les utilisateurs',
        'ticket.participant_creator' => 'Créé par',
        'ticket.participant_remove' => 'Retirer',
        'ticket.participants_add_label' => 'Ajouter des utilisateurs',
        'ticket.participants_add_placeholder' => 'Saisissez des adresses e-mail séparées par des virgules',
        'ticket.participants_add_button' => 'Ajouter des utilisateurs',
        'ticket.participants_save_button' => 'Enregistrer',
        'ticket.manage_participants_button' => 'Gérer les utilisateurs',
        'ticket.participant_remove_confirm' => 'Voulez-vous marquer %s pour suppression ?',
        'ticket.participant_note_added' => 'Utilisateurs ajoutes : %s',
        'ticket.participant_note_removed' => 'Utilisateurs supprimes : %s',
        'ticket.unassigned' => 'Non encore assigné',
        'ticket.new_message' => 'Nouveau message',
        'ticket.new_message_placeholder' => 'Saisissez ici une mise à jour ou des informations supplémentaires.',
        'ticket.key_picker_tooltip' => 'Insérer des raccourcis clavier',
        'ticket.emoji_picker_tooltip' => 'Insérer un emoji',
        'ticket.reopen' => 'Rouvrir le ticket',
        'ticket.add_attachments' => 'Ajouter des pièces jointes',
        'ticket.preview_image' => 'Agrandir l\'image',
        'ticket.preview_file' => 'Afficher l\'aperçu du fichier',
        'ticket.preview_close' => 'Fermer l\'aperçu',
        'ticket.file_hint' => '20 Mo maximum par fichier.',
        'ticket.btn_save' => 'Enregistrer',
        'ticket.btn_reply' => 'Publier la réponse et envoyer un e-mail à l\'ICT',
        'ticket.show_original' => 'Afficher l\'original',
        'ticket.show_translation' => 'Afficher la traduction',
        'translation.loading_tooltip' => 'La traduction est en cours de chargement',
        'translation.error_tooltip' => 'La traduction a échoué. Cliquez pour les détails.',
        'translation.error_title' => 'Erreur de traduction',
        'translation.error_fallback' => 'Une erreur est survenue lors du chargement de la traduction.',

        // New ticket form
        'new_ticket.heading' => 'Créer un nouveau ticket',
        'new_ticket.intro' => 'Un ticket est automatiquement attribué à un employé ICT en fonction de la catégorie et de la charge de travail actuelle.',
        'new_ticket.title_label' => 'Titre',
        'new_ticket.title_placeholder' => 'Par exemple : Nouveau scanner nécessaire',
        'new_ticket.category_label' => 'Catégorie',
        'new_ticket.category_option' => 'Choisir une catégorie',
        'new_ticket.description_label' => 'Description',
        'new_ticket.description_placeholder' => 'Décrivez le problème ou la demande aussi clairement que possible.',
        'new_ticket.blocked' => 'Mon travail est entravé',
        'new_ticket.fully_blocked' => 'Je ne peux pas continuer à travailler jusqu\'à ce que ce problème soit résolu',
        'new_ticket.requester_label' => 'Utilisateur',
        'new_ticket.requester_list_label' => 'Utilisateurs (la première adresse est le demandeur)',
        'new_ticket.requester_placeholder' => 'nom@kvt.nl (facultatif, pour créer un ticket au nom de quelqu\'un d\'autre)',
        'new_ticket.requester_hint' => 'ICT uniquement : cette adresse e-mail sera utilisée comme demandeur si elle est renseignée.',
        'new_ticket.requester_list_hint' => 'ICT : saisissez une ou plusieurs adresses e-mail.',
        'new_ticket.participants_label' => 'Utilisateurs supplémentaires',
        'new_ticket.participants_placeholder' => 'nom1@kvt.nl, nom2@kvt.nl',
        'new_ticket.participants_hint' => 'Ajoutez des collègues qui doivent aussi voir ce ticket dans Mes tickets.',
        'new_ticket.attachments_label' => 'Captures d\'écran ou documents',
        'new_ticket.btn_submit' => 'Soumettre le ticket',

        // Template tickets
        'template_ticket.heading' => 'Créer un ticket modèle',
        'template_ticket.intro' => 'Créez un ticket à partir de fragments de modèle et choisissez une catégorie de modèle.',
        'template_ticket.category_label' => 'Catégorie de modèle',
        'template_ticket.assignee_label' => 'Attribution',
        'template_ticket.assignee_auto' => 'Auto',
        'template_ticket.due_date_label' => 'Date d\'échéance',
        'template_ticket.title_label' => 'Nom du ticket',
        'template_ticket.title_placeholder' => 'Par exemple : Préparer un laptop pour un nouvel employé',
        'template_ticket.preview_label' => 'Aperçu du ticket',
        'template_ticket.preview_hint' => 'L\'aperçu correspond à la description finale du ticket (fragments joints par des sauts de ligne).',
        'template_ticket.create_button' => 'Créer le ticket modèle',
        'template_ticket.templates_heading' => 'Fragments de modèle',
        'template_ticket.create_template_heading' => 'Créer un modèle',
        'template_ticket.edit_heading' => 'Modifier le modèle',
        'template_ticket.template_name_label' => 'Nom',
        'template_ticket.template_name_placeholder' => 'Par exemple : Setup nouvel utilisateur',
        'template_ticket.template_body_label' => 'Texte',
        'template_ticket.template_body_placeholder' => 'Saisissez ici le fragment de modèle.',
        'template_ticket.create_template_button' => 'Enregistrer le modèle',
        'template_ticket.save_template_button' => 'Enregistrer les modifications',
        'template_ticket.delete_template_button' => 'Supprimer le modèle',
        'template_ticket.edit_template_button' => 'Modifier',
        'template_ticket.new_template_button' => 'Nouveau modèle',
        'template_ticket.modal_close' => 'Fermer',
        'template_ticket.back_to_list' => 'Retour à la liste',
        'template_ticket.delete_confirm' => 'Voulez-vous vraiment supprimer ce fragment de modèle ?',
        'template_ticket.empty_templates' => 'Aucun fragment de modèle pour le moment.',
        'template_ticket.select_template_error' => 'Sélectionnez au moins 1 fragment de modèle.',

        // Settings
        'settings.heading' => 'Paramètres par utilisateur ICT',
        'settings.intro' => 'Activez ou désactivez des catégories par collègue ICT et marquez les employés absents. Les nouveaux tickets sont automatiquement attribués au collègue disponible le moins chargé.',
        'settings.regular_categories_heading' => 'Catégories de tickets régulières',
        'settings.template_categories_heading' => 'Catégories de tickets modèle',
        'settings.col_user' => 'Utilisateur ICT',
        'settings.col_open_tickets' => 'Tickets ouverts',
        'settings.btn_save' => 'Enregistrer les paramètres',
        'settings.db_exists' => 'existe',
        'settings.db_missing' => 'manquant',
        'settings.dir_writable' => 'répertoire accessible en écriture',
        'settings.file_writable' => 'fichier accessible en écriture',
        'settings.yes' => 'oui',
        'settings.no' => 'non',

        // Statistics
        'stats.heading' => 'Statistiques ICT',
        'stats.intro' => 'Consultez ici les totaux, les performances par employé ICT et les temps d\'attente par utilisateur. Pour les tickets résolus, nous mesurons de <strong>créé</strong> à <strong>résolu</strong> ; les tickets ouverts comptent jusqu\'à <strong>maintenant</strong>.',
        'stats.total_tickets' => 'Nombre total de tickets',
        'stats.open_tickets' => 'Tickets ouverts',
        'stats.resolved_tickets' => 'Tickets résolus',
        'stats.waiting_order' => 'En attente de commande',
        'stats.per_ict' => 'Par employé ICT',
        'stats.col_ict_employee' => 'Employé ICT',
        'stats.col_handled' => 'Résolu',
        'stats.col_avg_open' => 'Temps ouvert moyen',
        'stats.col_max_open' => 'Temps ouvert le plus long',
        'stats.col_outstanding' => 'En cours',
        'stats.col_waiting_order' => 'En attente de commande',
        'stats.per_user' => 'Par utilisateur standard',
        'stats.no_user_stats' => 'Aucune statistique n\'est encore disponible pour les utilisateurs standard.',
        'stats.col_user' => 'Utilisateur',
        'stats.col_submitted' => 'Tickets soumis',
        'stats.col_avg_wait' => 'Temps d\'attente moyen',
        'stats.col_max_wait' => 'Temps d\'attente le plus long',
        'stats.col_avg_response' => 'Temps de réponse moyen',
        'stats.wait_note' => '* Le temps d\'attente inclut uniquement le temps dans les statuts <strong>soumis</strong>, <strong>en cours</strong> et <strong>en attente de commande</strong>. Le temps en <strong>résolu</strong> et <strong>en attente de l\'utilisateur</strong> n\'est pas compté. Le temps de réponse moyen correspond au temps moyen en <strong>en attente de l\'utilisateur</strong>.',
        'stats.sidebar_heading' => 'Tickets ouverts',
        'stats.sidebar_empty' => 'Aucun ticket ouvert.',
        'stats.no_assigned' => 'Non assigné',
        'bs.card_changed' => '#%d modifié',
        'bs.card_status' => 'Statut : %s',
        'bs.card_assigned' => 'Assigné à : %s',
        'bs.card_unassigned' => 'Personne',
        'bs.card_new_message' => 'Nouveau message',
        'bs.no_user_stats' => 'Aucune statistique disponible pour les utilisateurs normaux.',
        'bs.col_user' => 'Utilisateur',
        'bs.col_submitted' => 'Tickets soumis',
        'bs.col_avg_wait' => 'Temps d\'attente moyen',
        'bs.col_max_wait' => 'Temps d\'attente le plus long',
        'bs.col_avg_response' => 'Temps de réponse moyen',
        'bs.wait_note' => '* Le temps d\'attente inclut uniquement le temps dans les statuts <strong>soumis</strong>, <strong>en cours</strong> et <strong>en attente de commande</strong>. Le temps en <strong>résolu</strong> et <strong>en attente de l\'utilisateur</strong> n\'est pas compté. Le temps de réponse moyen correspond au temps moyen en <strong>en attente de l\'utilisateur</strong>.',
        'bs.new_ticket_from' => 'Nouveau ticket de %s !',
        'bs.assigned_to' => 'Assigné à : %s',
        'bs.not_yet_assigned' => 'Pas encore assigné',

        // Flash messages / errors
        'flash.admin_only' => 'Seuls les utilisateurs ICT ont accès à la vue d\'ensemble des tickets.',
        'flash.attachment_not_found' => 'Pièce jointe introuvable.',
        'flash.attachment_missing' => 'Le fichier est manquant sur le serveur.',
        'flash.session_expired' => 'Votre session a expiré. Veuillez actualiser la page et réessayer.',
        'session.expired_popup' => 'Votre session a expiré. Enregistrez votre texte localement et actualisez la page pour vous reconnecter.',
        'session.auto_refresh_in' => 'Actualisation automatique dans %d secondes.',
        'flash.db_open_error' => 'La base de données n\'a pas pu être ouverte : %s',
        'flash.ticket_title_required' => 'Veuillez saisir un titre pour le ticket.',
        'flash.invalid_category' => 'Veuillez choisir une catégorie valide.',
        'flash.description_required' => 'Veuillez saisir une description.',
        'flash.blocked_inconsistent' => 'Vous ne pouvez indiquer que vous ne pouvez pas continuer à travailler que si votre travail est déjà entravé.',
        'flash.invalid_email' => 'Veuillez saisir une adresse e-mail valide dans le champ Utilisateur.',
        'flash.invalid_email_list' => 'Une ou plusieurs adresses e-mail sont invalides : %s',
        'flash.ticket_created' => 'Le ticket #%d a été créé et automatiquement attribué.',
        'flash.template_ticket_created' => 'Le ticket modèle #%d a été créé.',
        'flash.template_name_required' => 'Veuillez saisir un nom pour le fragment de modèle.',
        'flash.template_body_required' => 'Veuillez saisir un texte pour le fragment de modèle.',
        'flash.template_created' => 'Fragment de modèle créé.',
        'flash.template_updated' => 'Fragment de modèle mis à jour.',
        'flash.template_deleted' => 'Fragment de modèle supprimé.',
        'flash.template_not_found' => 'Fragment de modèle introuvable.',
        'flash.template_due_date_required' => 'La date d\'échéance est obligatoire.',
        'flash.template_due_date_past' => 'La date d\'échéance ne peut pas être dans le passé.',
        'flash.template_selection_required' => 'Sélectionnez au moins 1 fragment de modèle.',
        'flash.template_description_required' => 'Les modèles sélectionnés n\'ont produit aucun texte exploitable.',
        'flash.ticket_participant_add_none' => 'Aucun nouvel utilisateur n\'a été ajouté.',
        'flash.ticket_participant_added' => '%d utilisateur(s) ajouté(s) au ticket.',
        'flash.ticket_participant_removed' => 'Utilisateur retiré du ticket.',
        'flash.ticket_participants_saved' => 'Les modifications des utilisateurs ont été enregistrées.',
        'flash.ticket_participant_remove_requester' => 'Le demandeur d\'origine ne peut pas être retiré.',
        'flash.ticket_participant_minimum' => 'Au moins 1 utilisateur doit rester sur le ticket.',
        'flash.ticket_participant_remove_failed' => 'L\'utilisateur n\'a pas pu être retiré du ticket.',
        'flash.ticket_not_found' => 'Ticket introuvable ou inaccessible.',
        'flash.invalid_status' => 'Veuillez choisir un statut valide.',
        'flash.invalid_employee' => 'Veuillez choisir un employé ICT valide.',
        'flash.self_assignment_not_allowed' => 'Un ticket ne peut pas être attribué manuellement à son demandeur.',
        'flash.employee_away' => 'Cet employé ICT est marqué comme absent et ne peut pas recevoir de nouveaux tickets.',
        'flash.invalid_priority' => 'Veuillez choisir une priorité valide.',
        'flash.reply_empty' => 'Veuillez ajouter un message, une pièce jointe ou un changement de statut.',
        'flash.ticket_updated' => 'Le ticket #%d a été mis à jour.',
        'flash.settings_admin_only' => 'Seuls les administrateurs peuvent modifier les paramètres.',
        'flash.settings_saved' => 'Les paramètres de catégorie et les absences ICT ont été enregistrés.',
        'flash.unknown_action' => 'Action inconnue reçue.',
        'flash.db_error_prefix' => 'Erreur de base de données :',

        // Libellés d'affichage des statuts
        'status.ingediend' => 'soumis',
        'status.in_behandeling' => 'en cours',
        'status.afwachtende_op_gebruiker' => 'en attente de l\'utilisateur',
        'status.afwachtende_op_bestelling' => 'en attente de commande',
        'status.afgehandeld' => 'résolu',

        // Libellés d'affichage des catégories
        'category.hardware_bestellen' => 'commander du matériel',
        'category.software_bestellen' => 'commander un logiciel',
        'category.licentie_aanvragen' => 'demander une licence',
        'category.business_central' => 'Business Central',
        'category.hardwareproblemen' => 'problèmes matériels',
        'category.softwareproblemen' => 'problèmes logiciels',
        'category.web_app_problemen' => 'problèmes d\'application web sleutels.kvt.nl',
        'category.anders' => 'Autre',
        'category.laptop_klaarmaken' => 'Préparer un laptop',
        'category.telefoon_klaarmaken' => 'Préparer un téléphone',

        // Libellés de priorité (sans préfixe numérique)
        'priority.label.0' => 'Normal',
        'priority.label.1' => 'Entravé',
        'priority.label.2' => 'Bloqué',

        // Unités de temps pour formatDurationSeconds
        'duration.year' => 'an',
        'duration.years' => 'ans',
        'duration.month' => 'mois',
        'duration.months' => 'mois',
        'duration.week' => 'semaine',
        'duration.weeks' => 'semaines',
        'duration.day' => 'jour',
        'duration.days' => 'jours',
        'duration.hour' => 'heure',
        'duration.hours' => 'heures',
        'duration.minute' => 'minute',
        'duration.minutes' => 'minutes',
        'duration.less_than_minute' => 'moins d\'1 minute',

        // Divers
        'datetime.unknown' => 'Inconnu',
        'flash.status_changed_to' => 'Statut modifié en %s.',
        'flash.attachment_upload_error' => 'La pièce jointe "%s" n\'a pas pu être téléchargée.',
        'flash.attachment_too_large' => 'La pièce jointe "%s" dépasse 20 Mo.',

        // Notifications par e-mail
        'email.subject_new_ticket' => 'Nouveau ticket #%d',
        'email.subject_created' => 'Le ticket #%d a été créé',
        'email.subject_update' => 'Mise à jour du ticket #%d',
        'email.subject_assigned' => 'Le ticket #%d vous a été assigné',
        'email.subject_user_reply' => 'Réponse de l\'utilisateur sur le ticket #%d',
        'email.subject_escalation' => 'Escalade ticket #%d',
        'email.subject_participant_added' => 'Vous avez été ajouté au ticket #%d',
        'email.intro_new_ict' => 'Un nouveau ticket ICT a été soumis.',
        'email.intro_created_self' => 'Votre ticket a été reçu par l\'ICT.',
        'email.intro_created_other' => 'Un ticket a été créé en votre nom.',
        'email.intro_update' => 'L\'ICT a mis à jour votre ticket%s',
        'email.intro_update_status' => ' et modifié le statut.',
        'email.intro_update_no_status' => '.',
        'email.intro_assigned' => 'Un ticket ICT vous a été réassigné.',
        'email.intro_user_reply' => 'Le demandeur a répondu à un ticket.',
        'email.intro_escalation' => 'Le ticket est ouvert depuis longtemps sans réponse.',
        'email.intro_participant_added' => 'Vous avez été ajouté comme utilisateur à ce ticket.',
        'email.btn_view' => 'Voir le ticket',
        'email.field_category' => 'Catégorie',
        'email.field_requester' => 'Demandeur',
        'email.field_assigned' => 'Assigné à',
        'email.field_status' => 'Statut',
        'email.field_updated' => 'Mis à jour',
        'email.not_assigned' => 'Pas encore assigné',
    ],
];

/**
 * Functies
 */

/**
 * Geeft het pad naar het user-prefs bestand voor een e-mailadres.
 * Geeft null terug als het e-mailadres niet beschikbaar / onveilig is.
 */
function getUserPrefsPath(string $email): ?string
{
    $email = strtolower(trim($email));
    if ($email === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
        return null;
    }
    $dir = __DIR__ . '/../data/user_prefs';
    $filename = preg_replace('/[^a-z0-9._\-]/', '_', $email) . '.json';
    return $dir . '/' . $filename;
}

function loadUserPrefs(string $email): array
{
    $path = getUserPrefsPath($email);
    if ($path === null || !is_file($path)) {
        return [];
    }
    $data = json_decode(file_get_contents($path), true);
    return is_array($data) ? $data : [];
}

function saveUserPref(string $email, string $key, mixed $value): void
{
    $path = getUserPrefsPath($email);
    if ($path === null) {
        return;
    }
    $dir = dirname($path);
    if (!is_dir($dir)) {
        mkdir($dir, 0750, true);
    }
    $prefs = loadUserPrefs($email);
    $prefs[$key] = $value;
    file_put_contents($path, json_encode($prefs, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
}

function getCurrentLanguage(): string
{
    return (string) ($_SESSION['lang'] ?? 'nl');
}

/**
 * Geeft de vertaling voor $key in de actieve taal.
 * Extra $args worden via sprintf ingevoegd (voor %d, %s, etc.).
 */
function __(string $key, mixed ...$args): string
{
    $lang = getCurrentLanguage();
    $translations = TRANSLATIONS[$lang] ?? TRANSLATIONS['nl'];
    $string = $translations[$key] ?? (TRANSLATIONS['nl'][$key] ?? $key);

    return $args !== [] ? sprintf($string, ...$args) : $string;
}

/**
 * Page load
 */

// Laad opgeslagen taalvoorkeur als de sessie nog geen taal heeft
if (!isset($_SESSION['lang'])) {
    $prefEmail = strtolower(trim((string) ($_SESSION['user']['email'] ?? '')));
    if ($prefEmail !== '') {
        $savedPrefs = loadUserPrefs($prefEmail);
        if (isset($savedPrefs['lang']) && array_key_exists($savedPrefs['lang'], SUPPORTED_LANGUAGES)) {
            $_SESSION['lang'] = $savedPrefs['lang'];
        }
    }
}

// Verwerk taalwissel via ?lang= en sla permanent op
if (isset($_GET['lang']) && array_key_exists($_GET['lang'], SUPPORTED_LANGUAGES)) {
    $_SESSION['lang'] = $_GET['lang'];
    $prefEmail = strtolower(trim((string) ($_SESSION['user']['email'] ?? '')));
    if ($prefEmail !== '') {
        saveUserPref($prefEmail, 'lang', $_GET['lang']);
    }
}
